### ISSUE TITLE
Swapped key in Spanish ISO: "ºª" vs "<>"

### ISSUE THREAD

**Issue by d4nirod** [tekezo/Karabiner-Elements#1035]
When using Karabiner Elements on a MBP Sierra with a Spanish ISO keyboard and the same input source selected in MacOS the symbols printed by the key with Spanish ordinal "º" ("ª" with shift) located left to the "1" and the key for "<" or ">" located left of the "Z" are swapped. If I quit Karabiner the problem is gone.

**Comment by JZfi** [comment]
The same happens with a Finnish key layout both on the MBP's own keyboard and with external keyboards. The key left from Z (<>) and left from 1 (¶°) are swapped when Karabiner Elements is running. The OSX version is 10.12.6 and I'm running 11.1.0. This has happened for a longer time spanning many previous Karabiner Element versions.

**Comment by eMerzh** [comment]
Hi, 
seems i got the same thing in french, >< remapped to @#  

did you guys found a work arround  ?

**Comment by bytesplit** [comment]
I made this adjustment and everything is as expected now:
Preferences > Virtual Keyboard > Keyboard Type : Set to ISO

German layout Cherry PC-keyboard and configured as such in OS. It seems that by default Karabiner makes all keyboards ANSI.

**Comment by eMerzh** [comment]
💥 perfect @bytesplit ... forks for me! many thanks

**Comment by mkborregaard** [comment]
doesn't work for me.

**Comment by eMerzh** [comment]
eratum: it work but only for one of my keyboard, it's either the internal either the external.... not both

**Comment by bytesplit** [comment]
I actually deactivated Karabiner in Devices for the internal keyboard. I don't use it when I have the external connected (think docked) and it would indeed reverse-swap the keys. Seems like Apple thinks ANSI for it's own international keyboards.

So test with all attached keyboards!

**Comment by pascalpoizat** [comment]
same problem than @eMerzh :-(

**Comment by MonsieurLanza** [comment]
Swapped here in FR ISO Macbook here.

**Comment by deram** [comment]
For my Finnish MBP keyboard, ANSI is the correct setting, and it is ISO that gives swapped characters. for example the mentioned <> vs. §°

All seems fine with ANSI setting selected, except the mapping is different from the picture next to the radio-button.

**Comment by ohcibi** [comment]
I have a German MBP layout and I am using U.S. layout (which interestingly is not different from "British" regarding the ``` and `§` keys in macOS settings). Without karabiner it behaves "iso-like" i.e. ``` is right of `left shift` and `§` in the top left above `tab` and left of `1`. When karabiner is running I need to choose "ansi keyboard" in virtual keyboard setting which's image (correctly) doesn't even have the key I'm typing ``` with. The iso keyboard's image shows (also correctly) the layout which is active without karabiner-elements however when selected ``` and `§` are swapped (as in ansi). So at least for my situation karabiner is simply applying ansi layout when it should apply iso layout and the other way around. For sure karabiner is not doing what it shows in the layout images.

**Comment by OMA2k** [comment]
Hello everyone. The solution @bytesplit mentioned used to work (Preferences > Virtual Keyboard > Keyboard Type : Set to ISO), but recent versions of Karabiner-Elements don't have any ANSI/ISO option anymore so the swapped keys problem still remains. Now in the "Virtual Keyboard" tab you can just specify a numeric "Country Code", and  I don't know what number I should specify. How do I find what's the proper number for the Spanish keyboard layout?

**Comment by ohcibi** [comment]
@OMA2k the patch note show how to do it. It must be set in the systems settings now. Just open keyboard settings and on the first tab in the lower left is a button "Change keyboard type" which brings up macOS keyboard type detection.


HOWEVER this bug is not actually fixed. macOS (correctly!) detects an iso keyboard when I do what it tells to do to perform the detection. When I keep that selection and have karabiner running the keys are swapped as I described in my last comment (` `` ` (<-- those are two because its the only way i figured to at least print the character i'm talking about in markdown) with `§`). So now I have to choose the wrong keyboard type in the system settings and not in karabiner to make it work. I have not noticed any issues with that but I'd still like if karabiner would simply do the right thing and not the exact opposite. What makes it that hard to apply the correct layout? Any possibilities to help out?

**Comment by OMA2k** [comment]
@ohcibi : What "patch note" are you referring to? I've already done the "Change keyboard type" several times, but I still get the swapped keys when Karabiner is running.

What "wrong" keyboard are you selecting so it works correctly when Karabiner is running?

**Comment by ohcibi** [comment]
@OMA2k I'm running karabiner-elements 12.0.0 and I'm referring to the patch notes that are shown from the update window when "Checking for updates". Maybe you are still running 11.x?

Checkout the screenshot. When clicking the marked 'Change keyboard type' the dialog on the right appears and tells you to press the key right of the left shift key in order to detect the keyboard. The system then correctly detects an iso keyboard as shown in the screenshot on my system. This works fine without karabiner-elements.

However with karabiner-elements running **I need to choose _ANSI (United States and others)_ instead of the correctly detected _ISO (European)_**. If I keep the ISO one, the key right of the left shift key and the top left key (below of `ESC`)
 are swapped.

<img width="1139" alt="screenshot 2018-05-25 14 21 46" src="https://user-images.githubusercontent.com/61993/40544202-b6e5209a-6027-11e8-8600-ace48f8de412.png">

**Comment by OMA2k** [comment]
This unfortunately doesn't work for me.

If I try to detect the keyboard while Karabiner-Elements is running, when I press "><" I get the message "The keyboard can't be identified".

If I try to detect the keyboard with Karabiner-Elements closed, then it works, but even if I select ANSI instead of ISO, the "><" and "ªº" keys are swapped no matter if I run Karabiner-Elements or not.

To sum up:
- In ISO mode, "><" and "ªº" keys are swapped only when Karabiner-Elements is running.
- In ANSI mode, "><" and "ªº" keys are swapped no matter if Karabiner-Elements is running or not.

So I don't have the proper keys unless in ISO mode and with Karabiner-Elements closed.

Any suggestions?

**Comment by OMA2k** [comment]
This problem is still happening with the latest 12.1.5 version of Karabiner-Elements. The <> and ºª keys are still swapped in the Spanish keyboard. Please, fix it!!!

**Comment by vladdeSV** [comment]
This issue is happening at 12.2.2, with a Swedish MacBook Pro keyboard layout

**Comment by ohcibi** [comment]
As the stale bot has closed this issue and it hasn't been opened since then, without them developers even acknowledging the bugs existence, you guys should consider using better touch tool. It doesn't have such issues but it is also not for free though.

**Comment by OMA2k** [comment]
@ohcibi What better tool are you talking about?

**Comment by ohcibi** [comment]
I didn’t say „better tool“. I said „better touch tool“. Which is the name of the tool I’m using. Confusing, I know 8-).

**Comment by OMA2k** [comment]
I see. You could have typed "BetterTouchTool", which is the actual name of the app, rather than "better touch tool" all lowercase and with spaces between the words, which didn't look like an app name at all but just a passing comment about some "better touch tool". I ignored the "touch" part in my comment because that didn't make sense to me when we're talking about keyboards.

For people reading this, here's the link of the app's website: https://folivora.ai/

The pricing is not bad at all. $6.50 for 2 years of updates (and you can keep using the app after that period even if you don't get any more updates), or $20 for a lifetime license which also gives you access to other apps as well included in the price.

Sorry for the somewhat off-topic post, but this is relevant when the developer of Karabiner-Elements won't listen to our bug report at all!

**Comment by ohcibi** [comment]
@Oma2k i could have also ignored this issue entirely because I’m using better touch tool since months now. Sorry for telling you an alternative.

**Comment by OMA2k** [comment]
Did you really get offended by my comment? I just suggested you could have called it like it's actually called by its author, BetterTouchTool. I didn't mean to tick you off ;).
BTW, thanks for suggesting this app.

Well, I have tried it, but I can't seem to get it to do what I need: Globally swapping the Ctrl key and the Cmd key. The keyboard part in this app seems to be focused in shortcuts rather than single keys. Do you know how to configure this to swap these modifier keys?

**Comment by OMA2k** [comment]
@ohcibi And now you delete all of your posts here? Just because of a single innocent suggestion on the spelling of the app you mentioned? So you're removing useful information for everyone just because you somehow got offended by a light unimportant passing comment I made. Some people get so easiliy offended...

**Comment by OMA2k** [comment]
Well, bad news for me and anyone who wants to remap keys: One of the admins at the BetterTouchTool website told me that "BetterTouchTool is not a good tool for key remappings. You should consider using Karabiner Elements app for that"

Heh, yeah, so we're back to square zero :(

This issue has been plaguing a lot of users since at least 2 years ago. I hope the Karabiner-Elements developer can notice us and take a look at this issue.

**Comment by OMA2k** [comment]
And a couple of months later, and several updates the problem remains.

Why is this issue closed? This issue has NOT been resolved at all!!! :(

**Comment by AlexLeaP** [comment]
I solved it: I just randomly entered a 7 as the keyboard country code. The Mac than says my keyboard is not identified, so I click on identify; asks me to press the key next to Shift; asks me to select between ANSI, ISO or JIS, I select ISO and tadaaaa everything fine again! Hope this helps someone else as well!

**Comment by vtselfa** [comment]
Hi, you have a list of country codes to use [here](https://docs.oracle.com/cd/E25749_01/E25745/html/Clients-Keyboard-Country-Codes.html).
For spanish is 25. The only problem is that it may mess with your macbook keyboard, so when you want to use it you may have to change the code back to 0.

**Comment by aclementev** [comment]
I still have this same issue.
I can fix this by forcing a keyboard type change and pressing the corresponding key in either the external keyboard or the MBP's internal, but I can't make both work at the same type.

Both keyboards are the same Spanish ISO layout.

**Comment by OMA2k** [comment]
Since this problem was never fixed, my solution to the issue was adding a key mapping so "grave_accent_and_tilde (`)" gets swapped with "non_us_backslash" and viceversa (2 rules). By doing that, the keyboard is back to normal.

**Comment by aclementev** [comment]
Yes, I ended up finding that solution as well, and it solved it for me for the time being.

**Comment by omar1989omb** [comment]
Thanks @joppuyo , I have been looking for a solution to this problem for several days since I changed keyboard.

**Comment by Pablompg** [comment]
> @raine Have you tried selecting the external keyboard under **simple modifications** and creating a mapping from `` grave_accent_and_tilde (`) `` to `non_us_backslash` and vice versa? This should apply the change only to the external keyboard.

Life saver!

**Comment by elmart-devo** [comment]
Also bitten by this (spanish keyboard exchanging < and º keys). It's a pity this has been open and unresolved for so long.

**Comment by joppuyo** [comment]
> Also bitten by this (spanish keyboard exchanging < and º keys). It's a pity this has been open and unresolved for so long.

I'm actually not sure if this is a problem with Mac OS, keyboard vendors, or Karabiner Elements. My issue was specifically that an external keyboard had these two keys swapped and I used Karabiner Elements to fix this issue as [I wrote in my blog](https://siipo.la/blog/fixing-the-wrong-keyboard-layout-on-varmilo-va88mac-nordic). I think in this case the keyboard vendor was using some kind of spoofed Apple profile for the keyboard and this caused issues with the operating system.

But it could be that there's an actual bug in Karabiner related to these two keys changing when it's actually not intended.

**Comment by elmart-devo** [comment]
@joppuyo Yes, you may be right and this can be not Karabiner's fault but rather the device's.
It also happened to me with an external mechanical keyboard (a Newskill Pyros Ivory), and after posting the above, I did a lot more tries, and somehow I ended up in a stable situation where I have country code set to zero, with ISO Spanish Layout, and I don't need to exchange the keys anymore. But that was exactly my initial situation when I reported the mentioned malfunction. So I don't really know what happened. Maybe it was due to the device, maybe some Karabiner state, maybe some strange interaction between the two things.

Thanks for pointing that out, and I just leave here my correction to my previous comment for the record.

**Comment by gdguglielmo** [comment]
For those who have this issue:

In Karabiner Elements:

* Create a Simple Modification
    * grave_accent_and_tilde -> non_us_backslash
    * non_us_backslash -> grave_accent_and_tilde
    
 Worked for me for fixing the <> vs ºª issue.

**Comment by backpackerhh** [comment]
@gdguglielmo it worked like a charm for me. Thanks!

**Comment by rickyah** [comment]
This issue still happens on version 15.3.0 with a Spanish Apple Magic Keyboard, Model A1644 (launched in 2015) with the 65% layout:
![IMG_0421](https://github.com/user-attachments/assets/802ff264-f50d-4ea0-9a33-a389af975501)


Karabiner reports the keyboard as
```
Magic Keyboard (Apple Inc.)
Vendor ID:   1452 (0x05AC)
Product ID:    615 (0x0267)
```
![image](https://github.com/user-attachments/assets/8e4247d3-dbef-4058-ab82-7ecc9e6a0652)


Karabiner swaps keys º (the one to the left of the number 1 key) and < (the one to the right of the left shift key), so pressing the former actually inputs the latter, and viceversa

Keyboard is set to ISO in preferences. Curious thing is, if I switch to ANSI, the problem does not appear.

Workaround is either disable events for Apple Magic Keyboard if you don't need to change the behaviour of any key (in my case I use Karabiner to adjust another windows keyboard I use), or just create a simple Modification as stated by @gdguglielmo [here](https://github.com/pqrs-org/Karabiner-Elements/issues/1035#issuecomment-2271331665)
