### ISSUE TITLE
how to  map jkli to arrow when caps lock on

### ISSUE THREAD

**Issue by ethanchen** [tekezo/Karabiner-Elements#1039]
I can map `fn`+`j` to `left arrow`, but I don't know how to make it when `caps lock` **on** (without pressing key), and when caps lock off , it will turn to normal.

**Comment by iSwfe** [comment]
My solution is map `Capslock` to `fn`, and the key `fn` can use with others like `i`/`j`/`k`/`l`.
and then, I map `fn`+`spacebar` to work for `Capslock`, it can be a good idea that you can try.

**Comment by babyking** [comment]
Here's my way.

1.
![image](https://user-images.githubusercontent.com/478250/31582794-dc4a4a24-b152-11e7-92f1-1186c7c85dab.png)
2. in Keyboard Maestro
![image](https://user-images.githubusercontent.com/478250/31582802-f53254be-b152-11e7-8d82-a70899937b10.png)

**Comment by gitnix** [comment]
Hey @iSwfe . I use the old Karabiner in conjunction with Seil to map Capslock + "whatever combination of keys" to some key or combination of keys. Since you mention something that looks similar to what I'm after, I was wondering if you could let me know if something like this is possible with Karabiner Elements: `"capslock + right_command + j" = "option + left_arrow" ` ?
