### ISSUE TITLE
define a group of bundle_identifiers ?

### ISSUE THREAD

**Issue by kungfubozo** [tekezo/Karabiner-Elements#1054]
hi 
is there a way to define a group of bundle_identifiers for using in a condition, without the need to copy-n-paste the same set of bundle_ids onto each manipulators individually ?
thanks

**Comment by dqgthb** [comment]
I am curious as well. Basically I need to edit individual files every time I want add a single identifiers.

**Comment by IllyaMoskvin** [comment]
I'm also interested in this feature. I'm looking at some rules available on [Karabiner-Elements complex_modifications rules](https://ke-complex-modifications.pqrs.org/), e.g. [Windows shortcuts on macOS](https://ke-complex-modifications.pqrs.org/#windows_shortcuts_on_macos), and many of them have identical blocks of `bundle_identifiers`. It would be nice to have the option of refactoring them to be defined in one place rather than per-condition.
