### ISSUE TITLE
Delete key is Move to Trash

### ISSUE THREAD

**Issue by Mochnant** [tekezo/Karabiner-Elements#1081]
Is there a modification that will allow the delete key to act as Move to Trash?

Thanks!

**Comment by nguyenhimself** [comment]
Add a rule inside the json file to remap 'Delete' to '⌘ + Delete' while Finder is being focused (using bundle_identifiers). Shouldn't be hard.

**Comment by nguyenhuuhanhch** [comment]
I don't can modified and add new Json file in config floder (mean App don't understand which I put into)

**Comment by xcode-manolo** [comment]
Hi @nguyenhuuhanhch !!!
For adding your own **Complex Modifications** you must put the .json file into the **/Users/YourUserName/.config/karabiner/assets/complex_modifications/**, then into **_Karabiner-Elements/Complex Modifications_** tab, push **+Add Rule** and then select your rule from the list.  It's easy.  If your rule doesn't appear (the most frequent thing) is because it has a typo or a syntax error.
Have a great day !!!

**Comment by sshymko** [comment]
The following custom rule that maps Delete to Cmd+Backspace worked for me:

`~/.config/karabiner/assets/complex_modifications/_finder_custom.json`
```js
{
  "title": "Finder Custom",
  "rules": [
    {
      "description": "Use Delete as Move to Trash",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "delete_forward",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "key_code": "delete_or_backspace",
              "modifiers": ["left_command"]
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com.apple.finder"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by sshymko** [comment]
Submitted the above solution to Karabiner Elements:
https://github.com/pqrs-org/KE-complex_modifications/pull/320

**Comment by avatar-lavventura** [comment]
This did not work on my end :-(
