### ISSUE TITLE
Karabiner-Elements doesn't work on Mac OS Sierra

### ISSUE THREAD

**Issue by Sesamme** [tekezo/Karabiner-Elements#1094]
Just installed Karabiner Elements on new iMac with OS Sierra, and it doesn't work. It doesn't start itself, it doesn't change the keys I set. Even if I put it manually in Log-in items, it just opens the prefs window, and that's it.
Event Viewer doesn't register anything that was changed in Karabiner...

**Comment by 3rd3** [comment]
I am having the same problem under Sierra after downgrading from High Sierra. I think I accidentally skipped the step where it asks for enabling the accessibility privacy settings. Now, Karabiner-Elements does not show up in the privacy settings at all. I have tried restarts, downgrading to 11.0.0, and adding the app from the /Applications manually to the privacy settings, but none of that helped. I cannot find where the Karabiner AXNotifier app is located, otherwise I would try adding it manually too.

**Comment by simplyandyg** [comment]
I was having a similar issue. It was previously working, then I updated to the latest app version and everything stopped working. It would not save my settings or implement them. I uninstalled Karabiner and then restarted my mac and reinstalled Karabiner. Everything is working now. Hope this helps anyone else who comes across this issue.

**Comment by mattHawthorn** [comment]
I'm having the same issue with log message `[warning] [console_user_server] /Users/matthew_hawthorn/.config/karabiner/karabiner.json is not owned by a valid user.`, despite checking permissions on `karabiner.json` and even trying `chmod 777` on it and its parent folder. Version 11.5.0 on Sierra 10.12.6.

**Comment by 3rd3** [comment]
Upgrade to 11.5.0 fixed this for me.

**Comment by Sesamme** [comment]
I have  no idea how and when it happened, but it now all works fine! my version is 2.318, and Mac OS 10.12.6

**Comment by feuyeux** [comment]
Let Karabiner-Elements running, and "System Preferences > Security & Privacy > Click "Allow".
My KE version is `12.1.0` and OS version is Sierra `10.13.6`

**Comment by kannanmavila** [comment]
I had the same issue and turned out I had to go to `identify the keyboard` in `Preferences > Keyboard` and run the wizard. Fixed the issue for me.

The option doesn't appear on `Preferences > Keyboard` anymore hence no screenshot. Sorry.
