### ISSUE TITLE
Computer now stuck on restart

### ISSUE THREAD

**Issue by davidtkearns** [tekezo/Karabiner-Elements#1102]
I updated Karabiner Elements. As per the instructions I allowed this via security settings. Then a message said I needed to restart. Now my Mac is stuck on the initial “progress bar” during startup. Not sure if Karabiner is the cause? I cannot do anything in the machine now.

**Comment by zobie** [comment]
The same thing happened to me. I tried a number of approaches to repair things, but ultimately had to completely reinstall the OS.

**Comment by davidtkearns** [comment]
Oh dear. Fortunately I have a recent system image to restore to. A pain though - takes several hours. But I need his machine for work.

**Comment by davidtkearns** [comment]
As reference I have High Sierra with APFS disk format and FileVault active

**Comment by tekezo** [comment]
This problem seems not related with Karabiner-Elements, however booting from safe mode might save you.

Mac OS X: Starting up in Safe Mode
http://support.apple.com/kb/ht1455

**Comment by zobie** [comment]
This problem happened immediately after the Karabiner update, so I still believe that Karabiner must have triggered the issue. I was able to boot and log in as a Guest user, but was fully unable to log into my own user account (even in safe mode). I don't know whether it will be helpful, but the attached picture shows the verbose-mode output at the point my computer was stuck.

As mentioned above, I was unable to manually repair my laptop without doing a full reinstall of the OS. The system has now been running without issue (and without Karabiner) for the past several days.

I installed Karabiner-Elements 11.3.0 an hour ago, and have rebooted the system twice since then. So far everything seems to be working normally. So, I believe @tekezo is likely correct: While Karabiner may have triggered this issue, it does not seem to have been the core problem.


![untitled](https://user-images.githubusercontent.com/4442/32896260-c6f6772c-ca9f-11e7-8d2f-2903c0a2c7f6.jpg)
