### ISSUE TITLE
JSON formatting resets if rules are added from "Complex Modifications" tab

### ISSUE THREAD

**Issue by RuslanIsh** [tekezo/Karabiner-Elements#1108]
I reformatted JSON file to my liking (like several brackets in one line, combined several lines into one, etc) so it would look more "compact" on my screen. 
Whenever I add new rules from within the program itself, its "Complex Modifications" tab, JSON file formatting is reset to the default style. It takes way too much space and is difficult to parse for me. 
Is it a feature or is there a way to keep formatting intact?

**Comment by xcode-manolo** [comment]
Hi @RuslanIsh !!!
It's possible to change karabiner.json directly.  But if you make typos or bugs in the sintax, it can be reset to default file.  The most secure way to modify karabiner.json is:

Make a .json file with your own rule.

Put it into Complex Modifications folder (/Users/YourUserName/.config/karabiner/assets/complex_modifications/YourOwnComplexModificationFile.json).

Enter in Complex Modifications tab into Karabiner-Elements and push **Add Rule** and look for your own complex modification in the list an add it. If your rule doesn't appear (the most frequent thing) is because it has a typo or a syntax error.
That's all !!!

Have a great day !!!

**Comment by RuslanIsh** [comment]
Perfect!
