### ISSUE TITLE
Modify keys for bluetooth keyboard only 

### ISSUE THREAD

**Issue by antonmedv** [tekezo/Karabiner-Elements#1114]
Hi,

Why my bluetooth keyboard inactive? Why I can't select it?

![image](https://user-images.githubusercontent.com/141232/32715336-7ebb3ae6-c884-11e7-9a25-d6bc2e8ce2fa.png)

**Comment by antonmedv** [comment]
I can't check my DREVO KEYBOARD.

**Comment by tekezo** [comment]
Please confirm the latest beta version. (v11.3.1)

How to upgrade to the latest beta version:
https://pqrs.org/osx/karabiner/document.html#check-for-updates

Your bluetooth keyboard does not have own vendor id, thus Karabiner-Elements treat it as Apple devices and disable it since Karabiner-Elements ignore Apple pointing devices.
I've changed to enable devices which have keyboard interface.

**Comment by antonmedv** [comment]
Yes, its latest. Just downloaded from site.

**Comment by tekezo** [comment]
I updated the beta version.
Please upgrade from Preferences.

![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by seanleblanc** [comment]
I don't see this Devices tab at all? I also have a DREVO Calibur 71 and I'm trying to figure out how to swap the Alt Key and the Windows key. I'm using 10.22.0 of Karabiner.
