### ISSUE TITLE
Is to_if_alone timeout necessary?

### ISSUE THREAD

**Issue by JesseLeite** [tekezo/Karabiner-Elements#1125]
![screen shot 2017-11-15 at 9 45 53 am](https://user-images.githubusercontent.com/5187394/32841937-ced15ed2-c9e9-11e7-9d51-d48307b7999b.png)

Regarding the `to_if_alone` timeout, is it necessary?  Every key has a keydown, then a keyup right?  Can it not immediately check on keyup if any other karabiner events have fired?  I'm thinking if no other karabiner events have fired, post the `to_if_alone` key, otherwise if other events fired, then you know it was pressed with another key.  What does the timeout accomplish?  Just wondering if anything could be done to reduce the delay of `to_if_alone`?  🙂

**Comment by vogler** [comment]
I was just wondering the same. What's the maximum? I want to use space as a modifier - why can't it just fire whenever there was no other key pressed at the same time?

**Comment by jtrim** [comment]
> I want to use space as a modifier

I was just trying to achieve the same thing (specifically to use space as control if held down, otherwise space if alone), but I'm finding it difficult to adjust my typing to not get caught in the timeout period. It would be great to know if there's any way to make this configuration more responsive.

**Comment by tekezo** [comment]
`to_if_alone_timeout_milliseconds` works when you press the target key long. (See `About cancellation`).

https://pqrs.org/osx/karabiner/json.html#to-if-alone

**Comment by ugultopu** [comment]
@jesseleite

> if no other Karabiner events have been fired, post the `to_if_alone` key

It already does it. As @tekezo said, the point of `to_if_alone_timeout` is to give you the option to "change your mind" after you press a key.

For example, let's say that you have configured the return key so that it acts as the return key when pressed and released, and it acts as the right control key when pressed with other keys. Let's say that you were going to use a keyboard shortcut, Control-A. Since A is on the left side, you are supposed to use the right control, so that you won't be pressing both the modifier and the letter at the same time. Since the right control is the return key, you pressed the return key. Just before you were going to press A, you changed your mind. In other words, you pressed the return key but since you changed your mind, you didn't press any other keys.

Now, what will happen? When you release the return key, a newline will be printed (or an application will be launched, etc.). However, thanks to `to_if_alone_timeout`, if you wait this long, when you release the return key, nothing will happen. This way, you will be able to change your mind after pressing a key.

Regarding the second question:

> Just wondering if anything could be done to reduce the delay of `to_if_alone`?

That's actually what I'm wondering as well and that's what brought me here. Unfortunately, currently I don't have an answer for it.

**Comment by martisj** [comment]
> `to_if_alone_timeout_milliseconds` works when you press the target key long. (See `About cancellation`).
> 
> [pqrs.org/osx/karabiner/json.html#to-if-alone](https://pqrs.org/osx/karabiner/json.html#to-if-alone)

The link has been moved, see https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-alone/#about-cancellation

**Comment by TheDataSeneschal** [comment]
> @jesseleite
> 
> > if no other Karabiner events have been fired, post the `to_if_alone` key
> 
> It already does it. As @tekezo said, the point of `to_if_alone_timeout` is to give you the option to "change your mind" after you press a key.
> 
> For example, let's say that you have configured the return key so that it acts as the return key when pressed and released, and it acts as the right control key when pressed with other keys. Let's say that you were going to use a keyboard shortcut, Control-A. Since A is on the left side, you are supposed to use the right control, so that you won't be pressing both the modifier and the letter at the same time. Since the right control is the return key, you pressed the return key. Just before you were going to press A, you changed your mind. In other words, you pressed the return key but since you changed your mind, you didn't press any other keys.
> 
> Now, what will happen? When you release the return key, a newline will be printed (or an application will be launched, etc.). However, thanks to `to_if_alone_timeout`, if you wait this long, when you release the return key, nothing will happen. This way, you will be able to change your mind after pressing a key.
> 
> Regarding the second question:
> 
> > Just wondering if anything could be done to reduce the delay of `to_if_alone`?
> 
> That's actually what I'm wondering as well and that's what brought me here. Unfortunately, currently I don't have an answer for it.

Brilliant Explanation. Thanks. ✅
