### ISSUE TITLE
Magic mouse doesn't scroll under Karabiner 11.3.0

### ISSUE THREAD

**Issue by bobjbaker** [tekezo/Karabiner-Elements#1142]
If I run Karabiner (on macOS 10.13.1) then my Magic Mouse 2 won't scroll.  But it works fine on my other Mac, which has a similar spec, in particular both use the same type of mouse.

The difference is that my Mac has a cabled Apple keyboard with numeric keypad (product ID 592), while the other Mac has a small cordless keyboard (ID 617).  Also, and this may or may not be relevant, on my Mac Elements/Preferences/Devices lists the mouse as non-editable with 'Modify events' box checked, whereas on the other Mac it lists the mouse as non-editable but with the box **unchecked**.

Any suggestions?

**Comment by markfeit** [comment]
For what it's worth, I'm having a similar problem post-upgrade (OS X 10.13.1, Karabiner 11.3.0) where mouse and trackpad clicks are being treated as if the Shift key is being held down.  This means scrolling is being treated as left-right instead of up-down and does nothing if a window is wide enough not to need to scroll in that direction.  When editing text, clicking someplace in the text it selects the entire region between the cursor and where I clicked.  Clicking on a link in a web browser (I use Firefox) opens it in a new window.

I'm not positive this is induced by Karabiner, as it doesn't go away after exiting.  It could be something in the OS that Karabiner is triggering.  In any case, a reboot makes it go away for awhile.

**Comment by bobjbaker** [comment]
The behaviour for my keyboard, when Karabiner is enabled, differs from what you describe. 

- Mouse scrolling doesn't scroll the page left, right, up or down, and similarly nothing happens when any modifier key is held down (eg. Cmd-Scroll-Down doesn't zoom in). 
- Another effect is that the tracking speed increases greatly, so I need to reduce the setting in System Preferences if I use Karabiner.  

- And when I uninstall Karabiner everything returns to normal, without the need for a restart.

Perhaps the differences are due to the type of keyboard?
