### ISSUE TITLE
Slash/pipe key inverted with greater-than/less-than key

### ISSUE THREAD

**Issue by teejay-87** [tekezo/Karabiner-Elements#1198]
I'm experiencing this problem on an Italian MBP 2016 15" with TouchBar.

The "\|" key (upper left) is being swapped with "<>" key (left to Z) when Karabiner is active.

**Comment by PierBover** [comment]
Same here with a Spanish ISO keyboard, although my upper left key is the `º` key.

Any way to solve this? I can't seem to find these keys in Karabiner to change their behavior either.

**Comment by PierBover** [comment]
I couldn't completely solve the issue but I'll post my findings here for posterity.

I was able to return the top left key to normality with `non_us_bakslash` mapped to `grave_accent_and_tilde`.

The "greater than" key near the left shift I was able to find it with `grave_accent_an_tilde` but since there is no key in US keyboards I couldn't map it to anything to restore functionality.

![image](https://user-images.githubusercontent.com/226483/35486322-92fdefac-043a-11e8-805e-4e3907dfe465.png)

Hopefully the bug that fixes this switching will be solved.

**Comment by ryandel13** [comment]
This bug also occurs in the German Layout, it's impossible to map the ^ key. As I don't use it a lot the Answer from PierBover works, but not completely.

**Comment by fiunchinho** [comment]
This is still hapenning

**Comment by dozepih** [comment]
Yes

**Comment by mickeyl** [comment]
Same problem here. Odd.

**Comment by ryandel13** [comment]
Solved by migrating to Windows :-^




Holen Sie sich Outlook für Android







On Tue, Jan 7, 2020 at 5:22 PM +0100, "Dr. Mickey Lauer" <notifications@github.com> wrote:












Same problem here. Odd.

**Comment by mickeyl** [comment]
Ok, with https://github.com/pqrs-org/Karabiner-Elements/issues/439 my German (external) keyboard correctly swaps `<` and `>` with `^` and `°`.

**Comment by cecchisandrone** [comment]
Thank you @PierBover, it solved my issue
