### ISSUE TITLE
How to map key to non-deadkeys version using Karabiner Elements?

### ISSUE THREAD

**Issue by kbdluv** [tekezo/Karabiner-Elements#1205]
I use a US International keyboard (normal US layout + deadkeys), and I would like to use Karabiner Elements to map a key to the "non-deadkeyed" version of another key, so I can use it without the extra Spacebar hit. This is what I have so far in my `src/json/personal_kbdluv.json.erb`:

        {
            "description": "Post grave_accent_and_tilde if Caps Lock is pressed alone, left_shift if held down.",
            "manipulators": [
                {
                    "type": "basic",
                    "from": <%= from("caps_lock", [], ["any"]) %>,
                    "to": <%= to([["left_shift"]]) %>,
                    "to_if_alone": <%= to([["grave_accent_and_tilde"]]) %>
                }
            ]
        }

That is, I want my Caps Lock key to spit out ` or ~ (with Shift). With the code I have so far, the behavior is the same as pressing the normal `/~ key. What do I need to change? Thank you!

(Cross posting [from SO](https://stackoverflow.com/questions/48084604/how-to-map-key-to-non-deadkeys-version-using-karabiner-elements) in case someone here can provide help. Sorry if this is not the right place.)

**Comment by 23tux** [comment]
I was gonna ask nearly the same question. I'm on a germany keyboard layout, and the backticks as well as the tilde key are configured as dead keys (they need an extra spacebar hit). I just want to map them to be non-deadkeys.

**Comment by plehton** [comment]
I'm using Finnish keyboard layout and resolved this by making a new keyboard layout with Ukelele where I removed all the dead  keys from default symbol keys: bactick, tilde etc. Now I can map the keys just how I want.

**Comment by haakonstorm** [comment]
# Sorry to revive this old thread....
but SO link above was nixed and can't get this to work properly. 

First, thank you so much for Karabiner. It is an awesome tool, (albeit a little difficult to configure).

I'm on a scandiavian keyboard (Norwegian - macOS 10.15 (latest beta) - Apple Magic Keyboard (non-keypad, but affects all macos versions and all Mac keyboards. 

## Backtick
K-Eventviewer outputs `code 46 equal_sign` when hitting they backtick key alone.
When pressed alone, backtick is a dead key.  To get backtick, you must use `option` + `backtick` (and in these days with so much Markdown around, it's getting increasingly painful!)

Eventviewer outputs `key_down` `46` `equal_sign` `flags: left_alt` on hitting `option` + `backtick` simultaneously, in addition to the modifiers up/down: (And why do everything appear twice? I have a Logitech G Pro USB-Mouse (with Logitech G Hub software):

<img width="512" alt="image" src="https://user-images.githubusercontent.com/193781/64421674-6a682400-d0a2-11e9-94b1-842ffd89296f.png">

I can't find any *complex modifiers* to *exchange* these two 'functions' on the same physical key. Is it possible?

## Tilde

It is even worse getting to type `tilde`. The `tilde` character is on a key the eventviewer reports as `48 close bracket`, also a dead key. Hitting `option` + `tillde` is a third dead key. To get tilde, you must use `option` + `tilde` and then hit space. *carpal tunnel song playing in the far distance*

# Questions
1. Did anyone successfully create  some sort of modifier or other solution to remap these dead keys somehow, to make them dead only with modifier or otherwise if the dead keys must continue to be ... dead?

2. Is it possible to create more dead keys somehow, like some sort of vim-mode, on Scandinavian keyboards?

## Extra: config
```
  "input_source": {
        "input_source_id": "com.apple.keylayout.Norwegian",
        "language": "nb"
    },
    "system_preferences_properties": {
        "keyboard_types": [
            [
                {
                    "country_code": 0,
                    "product_id": 49285,
                    "vendor_id": 1133
                },
                40
            ],
            [
                {
                    "country_code": 0,
                    "product_id": 10203,
                    "vendor_id": 5824
                },
                40
            ]
        ],
        "scroll_direction_is_natural": true,
        "use_fkeys_as_standard_function_keys": true
    },
    "variables": {},
    "virtual_hid_keyboard_country_code": 0,
    "virtual_hid_keyboard_keyboard_type": "ansi"
}
```

**Comment by fiedl** [comment]
Has anyone found a solution to this? I would also like to remap dead keys to their non-dead versions, especially the backtics on a German keyboard.

**Comment by ramirez** [comment]
So any ideas how to solve this?

**Comment by MuhammedZakir** [comment]
Create a keyboard layout according to your needs. That's the best solution when it comes to dead-keys. If you just want to enter those characters, you can map those button to execute AppleScript, but there will be a slight delay (problematic if you type *fast*).

1. https://software.sil.org/ukelele/ - you can find tutorials online on how to use this.
2. You may also try Keyman in case you're familiar with that.

**Comment by martin-braun** [comment]
@MuhammedZakir Not really a fulfilling solution. Here are some insights why:

Deadkeys are useful when typing in foreign languages, but they are garbage in the terminal, like within vim. I.e. I have to type `^` and space to get `^` which results in jumping to the beginning of the line in vim. Absolute garbage.

I'm also looking for karabiner-only version, as I want to free myself from BetterTouchTool (too many dependencies). In BTT I can avoid that like so: 

<img width="879" alt="Screen Shot 2023-01-31 at 3 59 47 PM" src="https://user-images.githubusercontent.com/24259245/215795919-c7839899-c8e7-42da-8bfd-48e02e7214e3.png">

So yea, the problem is that karabiner alone cannot press additional keys, while in BTT I can tell it to press space after the key has been pressed, automatically.

**Comment by haakonstorm** [comment]
```JSON
                    {
                        "description": "Revive dead Tilde key on Norwegian keyboard",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "close_bracket"
                                },
                                "to": [
                                    {
                                        "key_code": "close_bracket",
                                        "modifiers": [
                                            "left_option"
                                        ]
                                    },
                                    {
                                        "key_code": "spacebar"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }

```

**Comment by haakonstorm** [comment]
@martin-braun This will work the same way as you appear to do now with BTT, i.e. as a keyboard macro typing two key strokes after each other. 

The other way around, I haven't found a way to do.

**Comment by martin-braun** [comment]
@haakonstorm I had no idea you can send multiple key sequences will Karabiner. This is exactly what I needed, I love it, thanks for sharing!

**Comment by josephtribulat** [comment]
Hello there! I had reached the same point as this thread does, trying to solve the same problem with my French tilde key, and then I noticed that it created problems with vim. Namely, a command that contains a tilde (like g~w) can't work because the additional keystroke, such as spacebar or right arrow, "breaks“ the command. Now I'm out of ideas.

Is there not a way to just insert a character instead of remapping to another key?

**Comment by martin-braun** [comment]
@josephtribulat Thanks for bumping this, because I found a solution around the problem that I like to share which is much better than BTT or Karabiner.

I installed Ukelele. It allows you to create new keyboard layouts from existing ones. You can edit keys and disable their dead key modifier behavior to just print those keys. I added new keyboard combinations to still fall back to the dead key mechanic, so that I can still access it if I truly need it.

Don't ask me for details how to operate the program, it was a set and forget a while ago, but you will find something on the internet for Ukelele.

**Comment by josephtribulat** [comment]
Oh, thanks @martin-braun. Actually I came from there: until now I dealt with these problems by making keyboard layouts with Ukulele. But it's not the most convenient solution if you want to do quick temporary tweaks, which is why I wanted to try to do everything with Karabiner instead... Too bad if it doesn't provide a way to deal with dead keys.

**Comment by momomo** [comment]
The issue with the limitation to what karabiner can react to is an issue .. we are also limited by the amount of custom super shortcuts we can create due to the limit of the avaialble characters to use.

**Comment by momomo** [comment]
I use ukelele myself, but it would be so much easier to just rely on karabiner for that as well as having more flexibility with characters to use from keyboard.
