### ISSUE TITLE
Using VimMode modifiers (HJKL + ctrl = arrow keys) with other modifiers at the same time.

### ISSUE THREAD

**Issue by tomarcher101** [tekezo/Karabiner-Elements#1279]
Okay so I've got the following complex modifications on.

![screen shot 2018-02-20 at 2 48 27 pm](https://user-images.githubusercontent.com/28492773/36430453-2256e004-164d-11e8-8855-81fa5bc13c5b.png)

I love being able to navigate with ctrl (which i have remapped to capslock) and HJKL. However, if I try and use these keys with an additional modifier, they do not work.

For example, I would like to be able to jump to the bottom of the page. Normally this would be done with CMD+DOWNARROW. I want to do it with the J key acting as the down arrow. However when i type CMD+CTRL+J, nothing happens.

Is there a way to get this to work?

Edit: I got these modifications from https://pqrs.org/osx/karabiner/complex_modifications/

**Comment by sgosztyla** [comment]
I think that's because the "Vi Style Arrows" rules have the optional parameter set to "caps_lock" meaning that's the only other key that can be pressed with the remapped arrows.

It looks like you could also just import the "Vi Mode, left_control + hjkl. shift/option/command + arrow working" rules and get what you want.

Or you can modify this file:
 ~/.config/karabiner/karabiner.json 

And set the optional parameter from "caps_lock" to "any" or whatever keys you want it to work with.

**Comment by tomarcher101** [comment]
Yeah this modification does exactly what I want. Thank you very much!
