### ISSUE TITLE
Fn key only shows F1, F2... on Touch Strip once (Karabiner Elements 11.6, macOS 10.12.6)

### ISSUE THREAD

**Issue by InnerPortal** [tekezo/Karabiner-Elements#1281]
I have my touch strip (on 15-inch, 2017 MBP) set to show the standard function keys (F1, F2, etc.) when the "fn" key is pressed. 

When Karabiner-Elements is not running, all is fine. When it is running, the "fn" only show the function keys once. Subsequent "fn" presses do not change the touch strip.

I cleared by Karabiner configuration to ensure that there was nothing interfering.

Note that I do see the following warning in the log:

```
[2018-02-22 12:45:44.114] [warning] [grabber] We cannot grab Apple Internal Keyboard / Trackpad (device_id:3) while any modifier flags are pressed. (fn )
```

Any hints are appreciated!

**Comment by InnerPortal** [comment]
And annoyingly enough, it's working again. Tried reinstalling/rebooting to no avail, and older versions. Went back to 11.6.0 again and I was still seeing the incorrect behavior until just a minute or so ago, when my function key started working again!

Unless someone has a clue as to what might have happened, I'll close this ticket later...

**Comment by Jimmy34742** [comment]
I have exactly the same computer and configure the touch bar to show the Fn keys just like you. I've observed the following pattern: "initially," the Fn keys don't show. After a short time of doing the routine things I usually do on my computer, the touch bar starts behaving normally for the rest of the time.

I put "initially" in quotes because i'm not 100% clear what makes the problem occur. It's either after a reboot, an update of K-E, or a restart of K-E. But I don't think either of those three conditions will make the problem happen every single time. In any case, the problem magically disappears after a short time of doing stuff, but it's not clear what stuff clears the problem. But then problem doesn't occur until the next "initially," which is a long time so that I don't find the problem too annoying.

**Comment by InnerPortal** [comment]
Problem has reoccurred. Looks like I won't be using Karabiner for the time being :( Also have another issue where modifier+Fn key turns into just Fn even if there are no rules active... Perhaps that's another issue though.

**Comment by ohcibi** [comment]
I also have the same problem and want to add that for me it appears to not work for a certain time and then eventually the fn key will show the function keys while karabiner-elements still maintains its modifications I want and it seems to go like that until I reboot.
