### ISSUE TITLE
Logitech Gaming Software Conflict

### ISSUE THREAD

**Issue by ghost** [tekezo/Karabiner-Elements#132]
When starting Karabiner Elements first and after Logitech Gaming Software with Logitech G502 Proteus connected, the softwares conflict and it shows that you should update your Mouse Firmware. 

If I start first the Logitech Software and after Karabiner everything is ok. 
![screen shot 2016-09-24 at 18 41 11](https://cloud.githubusercontent.com/assets/742355/18809814/8d5a06c6-8286-11e6-9e6d-e13412308220.png)

**Comment by shemerey** [comment]
Have some issue with `G700s`

**Comment by anzyliao** [comment]
have same issue with G602

**Comment by Katzen-Gott** [comment]
I've got similar issue with G610 keyboard: Logitech gaming software sees that keyboard is connected, but cannot change its settings (adjust lighting, manage profiles, and such). Works fine if I first open Logitech and then open karabiner-elements, it works OK, but if I reconnect my keyboard, I need to stop karabiners-elements, restart logitech software and then start karabiner-elements again.

**Comment by owenzhao** [comment]
I have this issue with High Sierra 10.13.1. My device is Logitech G502 mouse.

**Comment by dev3395** [comment]
Same issue with Logitech G910 keyboard and G602 mouse on macOS 10.13.2.

**Comment by owenzhao** [comment]
@dev3395 Did you use APFS with case-sensitive in your disk? I found that was the issue. Because Logitech's game software didn't compatible with case-sensitive file system, which leads two setting profiles. 

The file is located in "~/Library/Preferences/com.logitech.gaming.plist", the correct file name should be "com.logitech.Gaming.plist". In a case-insensitive file system, the two files point to the same file, but in a case-sensitive file system, there are two stand-alone files.

**Comment by owenzhao** [comment]
@dev3395 For myself, I did a CCC (Carbon Copy Cloner) backup and restore, then it worked. I had to do that because I must format the file system to APFS case-insesitive. CCC reported me the file name duplicates, as I intended backing up from a case-sesitive file system to a insensitive one.

You said just changing the file name didn't work. So maybe the key is on those files that CCC didn't backup, like caches.

Here is the files and folders that CCC won't backup. If you have time, you can see if any of them are related to Logitech.

[Some files and folders are automatically excluded from a backup task](https://bombich.com/kb/ccc4/some-files-and-folders-are-automatically-excluded-from-backup-task)

**Comment by synapse709** [comment]
Same issue, still present in June 2019 with G602 mouse

**Comment by shuhu3** [comment]
Having the same issue with my G910 keyboard. None of the G keys work when Karabiner-Elements is enabled.

**Comment by drewwells** [comment]
starting logitech hub before karabiner workaround still works

**Comment by dmrickey** [comment]
I know nothing about macs and if I wasn't so used to windows I wouldn't have to use Karabiner. Karabiner is "already on" when I boot up my mac. How do I "start logitech hub before karabiner"?

**Comment by dmrickey** [comment]
Anyone?

**Comment by dmrickey** [comment]
> starting logitech hub before karabiner workaround still works

Someone please answer me..

**Comment by drewwells** [comment]
Quit karabiner, start LGS, start karabiner. I stopped using LGS entirely and life is better

**Comment by dmrickey** [comment]
> Quit karabiner, start LGS, start karabiner. I stopped using LGS entirely and life is better

Thanks. Is there any way to automate that on a mac? There are some things that karabiner can't do that I'm hoping I can accomplish with some LGS macros.

**Comment by dmrickey** [comment]
Yeah, when I "quit" karabiner it appears to just close as it's still running

**Comment by Eran-ARPalus** [comment]
I still have a problem with this. Karabiner just overrides GHub's access. Is there a way for both of them to operate simultaneously?
