### ISSUE TITLE
Why does exchanging £ shift-3 and # option-3 break Gmail delete?

### ISSUE THREAD

**Issue by kirbyj** [tekezo/Karabiner-Elements#1336]
I am on macOS 10.13.4 with a UK (British) keyboard. This means by default, shift-3 = £ and option-3 = #. As a result, shift-3 in Gmail (with keyboard shortcuts turned on) does not delete as expected.

The known workaround is to enable the Custom keyboard shortcuts in Gmail Labs, and to assign option-3 as an alternate shortcut for shift-3. This works fine.

However: if the Karabiner "Exchanging £ shift-3 and # option-3" complex modification is enabled -- which results in the the correct behaviour in all macOS applications -- the Labs functionality breaks.

Presumably, this is due to something funky Gmail is doing. But I can't for the life of me figure out what. Once the Karabiner modification is enabled, how can Gmail tell the keystrokes apart?

**Comment by crowbarz** [comment]
On macOS 13.3.1, instead of using Karabiner to remap £, #, \ etc. you can set the system keymap to British - PC to get Gmail shortcuts like '#' to mostly work properly on PC keyboards. A few sequences still don't work, such as Cmd+\ to remove formatting text when composing an e-mail, and it's a bit weird to use ` to cycle forward between inboxes and ~ to cycle back as they are on different keys.
