### ISSUE TITLE
computer sleep not functioning with karabiner active

### ISSUE THREAD

**Issue by limmers2015** [tekezo/Karabiner-Elements#1371]
Hello,

When I have Karabiner active on my iMac (2011, running sierra OS, not high sierra), the usual key command for sleep (_Control+Shift+Eject_) does not function. Neither does _Control+Eject_, then _S_ from the GUI. Have I messed something up? I have remapped only the function keys, nothing else, and only up to _f16_. I have the _press command q twice to close app_ complex mod active, and nothing else.

Seperate question:

Is there any way to  remap a key ONLY in a specific app? I have a program on my computer that closes instantly upon pressing _esc_, and I want to disable this, as I use spotlight a lot and am constnatly bumping it one too many times. I have looked, but I cannot for the life of me find how to do this.

Thank you for your time and help (as well as making such an **amazing** app!).

limmers2015

**Comment by tekezo** [comment]
Please follow this instruction:
https://pqrs.org/osx/karabiner/help.html#control-eject

> Seperate question:

Generally, you can do it with complex modifications.
https://pqrs.org/osx/karabiner/json.html#condition-definition-frontmost-application

However, spotlight is one of exception.
macOS does not recognize apps which does not have a menu as separate application.
Since, unfortunately, you cannot a configuration which is enabled only on spotlight.

**Comment by limmers2015** [comment]
Thank you for the advice, but my keyboard doesn't have fn. I have tried to remap f13 to be fn, but it doesn't seem to mesh with the complex modification properly. Any way around that? 

Thank you for the info regarding the esc modification. It is disappointing news, but still thank you. I use spotlight as a calculator in my geometry program, and the geometry program closes instantly upon an esc push. Just another thing I have to live with. 

Thank you again. It's really great when the software developer is there for those that use their software.

limmers2015
