### ISSUE TITLE
Create karabiner.json.bk.timestamp when overwriting config?

### ISSUE THREAD

**Issue by endrebak** [tekezo/Karabiner-Elements#1435]
I just lost a days work or more because I had been stupid and not backed up my karabiner config. Could you make it so that when karabiner wants to overwrite the config, it creates a backup of the old file?

Thanks for karabiner btw, loving it.

**Comment by tekezo** [comment]
Sounds good!
I changed to create automatic backups since v12.1.2.

(Karabiner-Elements creates `~/.config/karabiner/automatic_backups/karabiner_YYYYMMDD.json` before updating the karabiner.json if the file does not exists.)

You can confirm the feature in the latest beta version.
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by endrebak** [comment]
Great work :) What will happen if two configs are overwritten in the same day though? Then you might potentially lose the original. 

Events:
```
Karabiner changes config, creates backup karabiner_YYYYMMDD.json
Then karabiner changes config again, creates backup karabiner_YYYYMMDD.json
```

Now the first config is lost. If seconds/milliseconds are added to the timestamp, this is easily avoided :)

**Comment by tekezo** [comment]
The backups will be created frequently, for example, at switching a profile.
So I decided to make a backup per day.
I believe we can restore a configuration from a yesterday's backup.

**Comment by endrebak** [comment]
But I worry about the scenario where two backups are created in a day. Then the first will be overwritten. Anyways, thanks :)

**Comment by tekezo** [comment]
The backup will not be overwritten.
Karabiner-Elements keeps the first one.
