### ISSUE TITLE
Installed 12.1.0 and the kernel extension is missing

### ISSUE THREAD

**Issue by jpillora** [tekezo/Karabiner-Elements#1451]
Successfully installed though:

```
$ kextstat | grep -v apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
```

Which seems to be resulting in:

```
warning] [grabber] virtual_hid_device_client is not connected yet. Please wait for a while.
```

Is there a way to manually install the kext?

**Comment by strindberg** [comment]
I saw the same thing and tried doing it manually, but with no luck:

% sudo /sbin/kextload '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext'
/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext failed to load - (libkern/kext) authentication failure (file ownership/permissions); check the system/kernel logs for errors or try kextutil(8).

% sudo kextutil -nt '/Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext'
Kext rejected due to insecure location: <OSKext 0x7fb85d528a40 [0x7fffa669baf0]> { URL = "file:///Library/StagedExtensions/Library/Application%20Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext/", ID = "org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800" }
Kext rejected due to insecure location: <OSKext 0x7fb85d528a40 [0x7fffa669baf0]> { URL = "file:///Library/StagedExtensions/Library/Application%20Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext/", ID = "org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800" }
Diagnostics for /Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v060800.kext:

**Comment by jpillora** [comment]
Searched Console.app for "kext" and found the OS complaining that it could not install kext from insecure location "StagedExtensions" (lost the error now...).

I need Karabiner (and a few other kext-dependent apps) so I used a heavy handed approach:

* Restart holding down Command-R
* Terminal
* `csrutil disable`
* Restart

This disables SIP entirely and should allow all kexts to be installed. Will report back if I find the real fix.

**Comment by strindberg** [comment]
Yes, that is my temporary solution as well, until there is a real fix.

**Comment by strindberg** [comment]
My impression is that something went wrong during installation. I did grant karabiner the permission in the security preferences, but it somehow did not take, and now I can find no way to re-trigger the question. My problem is not the same as in #1017 .

**Comment by rdp** [comment]
If you attempt an install then go to "Security and privacy" immediately thereafter does it have a message "System software from developer Oracle was blocked" with an allow button?

**Comment by Rubenstein29** [comment]
I had the same problem and I can confirm that it's fixed when updating to the beta Karabiner Elements 12.1.4
