### ISSUE TITLE
Clone profile

### ISSUE THREAD

**Issue by a-b** [tekezo/Karabiner-Elements#1516]
I'd like to request a feature to clone profile.

**Comment by Marx1st** [comment]
I guess this would be a very small modification, but would really help us users!

**Comment by Devon7** [comment]
Profile inheritance beats profile cloning, because changes to the original(s) would be available in the clone(s) - e.g., a certain profile is just like the default profile except one particular complex rule is absent.

Might want a new TO form to change nothing (to override inheritance) or perhaps just change the FROM event into itself?
