### ISSUE TITLE
Rule Priority

### ISSUE THREAD

**Issue by rivaros** [tekezo/Karabiner-Elements#1534]
Have asked this before in #1164 but did not receive answer to the actual question (as I think).

Looks like in the below example manipulators of Rule 2 will not be executed, since Manipulator of Rule 1 goes first.

In that case - what is the purpose of "rules". We could just have one big rule with list of manipulators inside.

```
rules: [
{
  "description": "Rule 1",
  "manipulators": [
    {
      "from": {
          "key_code": "a"
      },
      "to": [
          {
              "key_code": "b"
          }
      ],
      "type": "basic"
    }
  ]
},
{
  "description": "Rule 2",
  "manipulators": [
    {
      "from": {
          "key_code": "a"
      },
      "to": [
          {
              "key_code": "c"
          }
      ],
      "type": "basic"
    }
  ]
}
]
```

**Comment by clemsam** [comment]
I don't quite understand your complaint: _WHY on earth_ would you want "a" remapped to "b" and next moment to "c" ?!?

IT's a strict principle that the first Rule (and even manipulator inside it) that "matches" or catches a key pressed by the user is ENOUGH.

If you want "Rule 2" sometimes instead of "Rule 1", define a "conditions" with "set_variable" to switch their order. If you generally prefer "Rule 2", put it in front of "Rule 1".

Rules to me are kind of "categories", where to place remaps or "scripts"…
