### ISSUE TITLE
[some key] + [shift] + [u] not working

### ISSUE THREAD

**Issue by inatomitk** [tekezo/Karabiner-Elements#1661]
I configured below, but it doesn't work.
Other keys work. only 'u' key doesn't work.

```
    "manipulators": [{
        "type": "basic",
        "from": {
          "key_code": "semicolon",
          "modifiers": {
            "optional": ["shift"]
          }
        },
        "to": [{
          "set_variable": {
            "name": "symbol",
            "value": 1
          }
        }],
        "to_after_key_up": [{
          "set_variable": {
            "name": "symbol",
            "value": 0
          }
        }]
      },
      {
        "type": "basic",
        "conditions": [{
          "type": "variable_if",
          "name": "symbol",
          "value": 1
        }],
        "from": {
          "key_code": "u",
          "modifiers": {
            "optional": ["shift"]
          }
        },
        "to": [{
          "key_code": "7"
        }]
      },
       ↓↓NOT WORKING↓↓
      {
        "type": "basic",
        "conditions": [{
          "type": "variable_if",
          "name": "symbol",
          "value": 1
        }],
        "from": {
          "key_code": "u",
          "modifiers": {
            "mandatory": ["shift"]
          }
        },
        "to": [{
          "key_code": "7",
          "modifiers": ["shift"]
        }]
      }]
```

**Comment by clemsam** [comment]
Does your code return _anything?_

Either "7" or whatever shift-"7" is on your keyboard?

**Comment by clemsam** [comment]
Weil, as you aren't answering, I guess that your code _ALLWAYS_ returns "7" when you press "u" !?!

Your 1st "u" manipulator has an "optional" part which means it will _EVERY time_ be invoked, no matter if shift is pressed or not, resulting in an output of "7".
This on the other hand means that your 2nd "u" manipulator _will NEVER be invoked_ since the 1st one already "captured" your key "u".

**_A key press is NOT passed on to a following manipulator if it meets conditions of a previous one._**

At least this is true if your code is in the sequence as posted above.

**Comment by inatomitk** [comment]
sorry for my late reply.

> Does your code return anything?

not anything returns.

Either "7" or whatever shift-"7" is on your keyboard?

> yes. I use macbook pro.

I want to use 'symbol' key, which is additional modifier key.
If I press 'u' and 'semicolon'(symbol key), I want to input '7'.
If I press 'u' and 'semicolon'(symbol key) and 'shift', I want to input 'shift 7.

**Comment by clemsam** [comment]
AFAIK, your code seems to work on my keyboard – but I have no semicolon key (and use an other one for testing).

Okay. I see 2 possible explanations (but there may be a 3rd one – the right one?):

1) There may already exist a "u" shortcut in the app that you are testing this in.

2) It _might_ be (_NOT_ likely) that because of its position to the right on keyboards, you accidentally press key "u" before you get to "shift" – seems a long shot to me.

**Comment by inatomitk** [comment]
thank you for your advice.

I tried to configure symbol key by using other keys (not 'u' key). but it also happens same problem.

ex1) symbol key using 'open_bracket'
→ only 'shift' + 'symbol key'(open_bracket) + 't' doesn't work.

ex2) set symbol key using 'quote'
→ only 'shift' + 'symbol key'(open_bracket) + 'u' doesn't work.

* I using us keyboard.
* I tried above in some apps.

**Comment by inatomitk** [comment]
> Does in ex1) work: symbol key + 't'?
> Does in ex2) work: symbol key + 'u'?

yes. both work. 'symbol key + 'shift' + ' u/t'` doesn't work.

**Comment by clemsam** [comment]
Okay, I'd say your problem is definitely "shift-u" and "shift-t".
From what you posted before "shift-a" (+ symbol) works.

So, is it _ONLY_ "u" and "t" that do not work in combination with symbol and shift, or are there any other keys that don't work?

**Comment by inatomitk** [comment]
> So, is it ONLY "u" and "t" that do not work (in combination with symbol and shift) or are there any other keys that don't work?

_ONLY_ 'u' and 't' don't work.

**Comment by clemsam** [comment]
That looks VERY much like they are "used" previously, maybe somewhere "totally else", even some app that "makes" its own definitions (Xcode does, and others too)?

You don't happen to have any other shortcuts defined in Karabiner that use "u" and "t"?

**Comment by inatomitk** [comment]
> This looks VERY much like they are "used" previously, maybe somewhere "totally else", even some app that "makes" its own definitions (Xcode does, and others too)?

I don't remember setting it up. I will try to find it.

> You don't happen to have any other shortcuts defined in Karabiner that use "u" and "t"?

No. I don't define any other shortcuts in Karabiner at least.

> Btw: in a repository of yours I saw an entire version of your code, but noticed that you (accidentally?) assigned "7" also to "from": …"key_code": "n".

I use 'n' in place of 'u' for now because 'u' is not working.

**Comment by clemsam** [comment]
Hm. I'm afraid (as your code works on my keyboard) that your problem is invoked by a circumstance that I cannot replicate.
Maybe s.th. to do with Japanese keyboards or apps that I don't use.

One _VERY LAST attempt_ to get insights might be to quit K-E temporarily and assign the "shift-u" shortcut via Apple's System-Prefs > keyboard > shortcuts > application shortcuts to a function for just one application, later for all applications.

I just tested this: if you try to assign a shortcut already in use it will NOT be accepted by the text field. Again: quite a long shot …

**Comment by inatomitk** [comment]
It does work using another keyboard!!

**Comment by clemsam** [comment]
Well, sounds kind of good … if using the other keyboard is an option for you.
At least I hope that my testing your code (without "your" issues) has helped you in the end to find a solution to this mysterious behaviour.

**Comment by inatomitk** [comment]
I found condition to occur.

 - mac os ( I investigated MacBook air & iMac)
 - bluetooth keyboard

**Comment by inatomitk** [comment]
I found it is probably mac problem, not karabiner-elements.
