### ISSUE TITLE
Bug: Mouse movement does not cancel "to_if_alone" (while the from key is pressed down)

### ISSUE THREAD

**Issue by BlueCrystal01** [tekezo/Karabiner-Elements#1673]
(While the from key is pressed down) "to_if_alone" does not get canceled if one moves the mouse cursor (tested on trackpad MacBook Pro 2018) . 

In the Reference Manual there stands: "to_if_alone is canceled if other events (keys, buttons or scroll wheel) is happen while the from key is pressed down." but this is not the case if i move the mouse cursor on my trackpad.

**Comment by BlueCrystal01** [comment]
Any news on this?

**Comment by chadawagner** [comment]
Running into the same issue. OS X 10.14.3, Karabiner-Elements 12.2.0

**Comment by cwagner22** [comment]
I don't think mouse movements should cancel `to_if_alone`. However, the mouse buttons definitely should and it's currently not working. I've been hoping for a fix for quite some time.
I've found a way to fix it for my mouse: in Karabiner-Elements Preferences > Devices, allow "modify events from this device" for my mouse.

Now my mouse buttons cancel `to_if_alone` but for my mackbook internal trackpad it's not possible since the option is grayed...

@tekezo

**Comment by mantheflan** [comment]
Any (more) updates on this? For me this is important for drawing software such as Inkscape, where a click has different effect depending on whether Ctrl or Alt is held down.
The solution given be @cwagner22 works perfectly for mice but not for the internal trackpad (option is grayed out). What is the explanation for this?
