### ISSUE TITLE
Sequential 'simultaneous' commands without releasing all keys?

### ISSUE THREAD

**Issue by sirdavidoff** [tekezo/Karabiner-Elements#1806]
I'm using K-E to define a `hyper` modifier key that I can also combine with other modifiers, e.g. mapping `hyper-cmd-j` to `page down`. Sample code below.

I often use these commands multiple times in a row, and the natural thing is not to release the modifier keys in between e.g.: `<hyper down><cmd down><j down/up><j down/up><j down/up><cmd up><hyper up>`. This worked in the original Karabiner, but doesn't in Karabiner Elements; I need to release all keys before I press any again.

Is there any workaround to avoid having to release all keys in between?

```
{
    "from": {
        "simultaneous": [
            {
                "key_code": "left_command"
            },
            {
                "key_code": "caps_lock"
            },
            {
                "key_code": "j"
            }
        ]
    },
    "to": [
        {
            "shell_command": "open -g hammerspoon://hypercmdj"
        }
    ],
    "type": "basic"
}
```

**Comment by LynnWalton** [comment]
My use case is entirely different but I think it **might** be related to needing this same kind of functionality.  I am DESPERATE to be able to have the full functionality that jeebak's touch cursor in the old Karabiner had, which used a held down space bar along with other keys for navigation but allowed the s key to be also held down with the space bar and the other nav keys in order to allow selection to occur while navigating. Likewise, the a key could also be held down to be able to add option so that a -> (move one char at a time) became option -> (move one word at a time).   I've studied jeebak's current touchcursor extended for karabiner-elements and also the mouse mode stuff and have experiemented and tried a bunch of things but I'm no where close to having this critical functionality I had with Karabiner.  

I would gladly pay someone that could make the above scenario work well (without timing issues).
:)
Pretty pretty please @tekezo  :) :)
