### ISSUE TITLE
Make the app explicitly ask for permission to update!

### ISSUE THREAD

**Issue by WebDevBooster** [tekezo/Karabiner-Elements#1836]
The version 12.3.0 had introduced breaking changes that made my keyboard completely unusable. 
That happened suddenly and while I was working because the app auto-updated to the new version without my permission.

I would like to see the default behavior of the app changed so that it NEVER updates without the user's explicit permission to do so. 

It is a huge disruption when suddenly, during a normal workday, the app suddenly breaks the entire keyboard layout making me unable to do any work and forcing me to spend hours on troubleshooting the issue. 

So, the updates should only happen when I explicitly confirm that it's OK to update. Never automatically. I'd like to log this as a feature request. Thanks.

**Comment by BosEriko** [comment]
I agree with this. But I guess on my case I might've clicked yes on an update prompt but then after it, I was unable to use my capslock as an esc/ctrl combo. I had to revert back to 12.2.0 just so I could have it back again. Not sure what I should change with my karabiner.json file so that I can upgrade to 12.3.0 safely.

**Comment by okyr-ux** [comment]
Version 12.3.0 asks if you want to update to 12.4.0.
