### ISSUE TITLE
The key above Tab and the key next to Left-Shift are incorrectly swapped in the Spanish, German and French keyboards (and probably more!)

### ISSUE THREAD

**Issue by OMA2k** [tekezo/Karabiner-Elements#1842]
I know this issue has been reported already, but since the other issue report is closed and has been ignored for **years**, I'm opening this new one in the hopes that it will get noticed.

For some reason, while Karabiner-Elements is running the keys "ºª\\" and "<>" are swapped in the Spanish keyboard. Closing Karabiner-Elements restores those keys to their original positions.

I don't know why the other report got closed, but this issue still has not been fixed.
Could it be finally fixed, please? If you need any help to find the problem, just ask.

Thank you!

**Comment by flxs** [comment]
I'm having the same issue with ^° and <> on German ISO layout. MacOS seems to consistently detect one of my two keyboards (external USB and internal Macbook one) as ANSI, though both are German ISO.
Changing the country code in Karabiner prompts MacOS to show the keyboard setup dialog, where it'll detect the correct type, but as soon as I unplug the external Keyboard, it all gets messed up again. Definitely not fixed for me either.

**Comment by Bibi** [comment]
+1
Swapped for French keyboard also. EventViewer sees:
- backslash (code 49) when I press `
- grave_accent_and_tilde (code 53) when I press <
- etc.

**Comment by flxs** [comment]
Workaround that has worked for me for the last month or so: 

1. Reboot the machine (to get a clean state, if you've been fiddling around with country code or the like)
2. Once hitting the issue the next time, just swap the two offending keys in Karabiner, just for the keyboard that's showing the issue. In my case, I had to swap `grave_accent_tilde` and `non_us_backslash` for my external Vortex Race 3.

Tested on Mojave and High Sierra with two different Vortex Race 3 and latest version of Karabiner Elements. I don't have a clue what's causing this, but that fixes the issue for me.

**Comment by OMA2k** [comment]
> just swap the two offending keys in Karabiner, just for the keyboard that's showing the issue.
> In my case, I had to swap `grave_accent_and_tilde` and `non_us_backslash` 

THANK YOU!!!!!!!!! This FINALLY fixed this issue for me! I didn't know I had to swap those specific keys, especially having in mind that in the Spanish keyboard the key next to Left Shift does not contain any "grave accent" or any "tilde". That key just contain the characters ">" and "<". Why is that still considered the "grave_accent_and_tilde" key by Karabiner-Elements?

Anyway, this trick worked. Thanks a lot! Now my only problem is that after 2 YEARS of having this issue (I don't get why it has been completely ignored for so long), I've grown accostumed of having these keys swapped, so now I have to un-learn that habit ;-)

**Comment by noeliajimenezg** [comment]
The same issue here with a Spanish ISO keyboard. Thanks @flxs for the workaround!

**Comment by turbanisch** [comment]
The bug is still there (German ISO layout).

**Comment by Bibi** [comment]
Same problem with brand new MBP (ISO keyboard type)!

**Comment by systemOverview** [comment]
I had the same issue on AZERTY but basically all of the characters except letters and numbers were incorrectly displayed on the event viewer, and I think I've stumbled upon a good workaround for any problematic character. 

What worked for me, is finding the current combination for it on Mac's keyboard viewer, then using that combination in the "to" block. I found this solution in one of the examples (Link : https://ke-complex-modifications.pqrs.org/#azerty_windows_like_combinations). 

 Example: 

`{
    "description": "Right command and '=' for \\ backslash",
    "manipulators": [
        {
            "from": {
                "key_code": "slash",
                "modifiers": { "mandatory": ["right_option"] }
            },
            "to": {
                "key_code": "period",
                "modifiers": ["left_option", "shift"]
            },
            "type": "basic"
        }
    ]
}`

The main issue was that when I just put backslash in the to key_code , it would print ` (accent grave) instead, it was mapping ' to backslash, but since backslash is a combination of keystrokes in azerty, when I hit that keystroke in the eventviewer it would only output the buttons that I've clicked and not the backslash in the events, and I wasn't able to figure out what key does Karabiner see as a a backslash. 

But since it has no issue with outputting the key name for single keystrokes, you can just press every key in your combination, (in AZERTY for me, the 'native' way to type a backslash is shift + option + ':', so you'd press every one of them in the event viewer and get it's code, for me the comma key code was shown as period), same thing for the from section (the '=' key code is shown as slash).

**Comment by andredasilvapinto** [comment]
Same problem with the Portuguese keyboard. Quite incredible that a bug like this (consistent and widespread) has been open (even though marked as closed) for so many years.

**Comment by oliverfrost1** [comment]
Same problem with Nordic keyboard
