### ISSUE TITLE
Caps Lock LED

### ISSUE THREAD

**Issue by gershik** [tekezo/Karabiner-Elements#1859]
The Caps Lock LED turns off when switching virtual desktops and turns back on in about a second, both with 'Manipulate LED' enabled or disabled.
macOS version: 10.14.4
Karabiner version: Karabiner-Elements 12.4.3
Your Mac hardware: MacBook Pro 2017 13" w/o Touch Bar
Your keyboard hardware: MacBook Keyboard

**Comment by Misoder** [comment]
I'm also experiencing this since a few days ago.

**Comment by braham-snyder** [comment]
I ran into this as well. I didn't see this issue until updating, just now, from Karabiner 12.6.0 to Karabiner 12.7.0, coinciding with a macOS update.

I just quit Karabiner, tapped the caps lock key and switched spaces (in an order I don't remember), then restarted Karabiner — now I am not seeing the issue.

The issue was only affecting my external, wired Apple keyboard, even when I used the internal keyboard to switch spaces.

I saw the issue even when I turned off "Manipulate LED" for the external keyboard.

I also still saw the issue even when I used a Karabiner profile w/ only default settings. 

macOS version: 10.14.6
mac hardware: MacBook Pro (Retina, 15-inch, Mid 2015)
keyboard: external
