### ISSUE TITLE
Not work in macOS 10.15

### ISSUE THREAD

**Issue by lilingzhi** [tekezo/Karabiner-Elements#1885]
macOS version: macOS 10.15 beta1
Karabiner version: Karabiner-Elements 12.5.0
Your Mac hardware: MacBook 12

**Comment by hoangtuanfithou** [comment]
Hi, is there update about this ?

**Comment by jasondonnette** [comment]
There is this issue that is tracking the same bug: https://github.com/tekezo/Karabiner-Elements/issues/1867 

It has some workarounds posted in there, but they stop working after a period of time so it is not fixed yet.

**Comment by hoangtuanfithou** [comment]
Thanks @jasondonnette I will give it a try

**Comment by aoenth** [comment]
I'm just waiting for the Caps Lock Delay removal feature to be fixed. Still using Karabiner Elements 11.6 as of right now. Unfortunately even 11.6's Caps Lock Delay removal feature doesn't work in 10.15 Beta. Please please look into it. Karabiner Elements is the last reason I'm still using a Mac.

**Comment by FengFeng-is-me** [comment]
I forgot whose sharing. 
But my app is still working，My MacOs version is 10.15.
 if you can't Solve it after read my solution，don't email to me.Because the app on my machine is working why you can't,I really don't know,And  I’m Chinese students，I can hardly read your emails.
some people may can't find the dir ,you had better Google it about how to find the bin Catalog.
![image](https://user-images.githubusercontent.com/32693877/60289818-e844dc00-9949-11e9-9065-3417ac01c844.png)

![image](https://user-images.githubusercontent.com/32693877/60289829-f0048080-9949-11e9-82b6-438b058ef3cd.png)

![image](https://user-images.githubusercontent.com/32693877/60290025-686b4180-994a-11e9-8871-e85df8c8bfa0.png)

**Comment by fefine** [comment]
you can use `hidutil` to remap key, for example remap right cmd to right ctrl
> hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x7000000E7,"HIDKeyboardModifierMappingDst":0x7000000E4},{"HIDKeyboardModifierMappingSrc":0x7000000E4,"HIDKeyboardModifierMappingDst":0x7000000E7}]}'

keycode:
E7: right gui(right command) 
E4: right control

refer: 
* https://apple.stackexchange.com/questions/283252/how-do-i-remap-a-key-in-macos-sierra-e-g-right-alt-to-right-control
* https://developer.apple.com/library/archive/technotes/tn2450/_index.html
* https://discussions.apple.com/thread/8133633

**Comment by iMcG33k** [comment]
https://note.wuze.me/temporary-resolution-of-karabiner-not-working-in-macos-catalina-beta

It works!!!

**Comment by iMcG33k** [comment]
https://note.wuze.me/temporary-resolution-of-karabiner-not-working-in-macos-catalina-beta

It works!!!
