### ISSUE TITLE
Is there a JSON schema for Karabiner configs?

### ISSUE THREAD

**Issue by dvdvdmt** [tekezo/Karabiner-Elements#1918]
I wander is there a [JSON schema](https://json-schema.org/) for Karabiner configs? This could tremendously improve experience of editing config files in modern code editors (Webstorm, VSCode, etc.) and simplify validation of those configs.

**Comment by LvChengbin** [comment]
Yep, you can find a JSON file `~/.config/karabiner` named `karabiner.json`, and you can update your settings by modifying this file directly.

**Comment by dvdvdmt** [comment]
It is not what I am looking for. I want a JSON-schema, not a config in a
JSON format.

**Comment by jch8ri** [comment]
It's in the reference manual of the website.

https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-disable-command-l-on-finder

**Comment by dvdvdmt** [comment]
Sure, I know where the manual is, but it is not what I was looking for.

**Comment by dragon788** [comment]
I think it might be possible to create a validator for the JSON from the API specs on the json.html page.

A static "schema" like XML uses might not be very useful since the JSON structure can change as the program changes, and it would be a lot of extra effort for Karabiner-Elements to parse the schema version and behave differently or throw special warnings if the schema isn't valid, where now I believe it probably just ignores elements it doesn't understand and uses the rest that it does.

Now if you just wanted auto-complete/intellisense, a kind of syntax highlighting and keyword validation might be more useful, and possible to automate given the rules on that page.

**Comment by tekezo** [comment]
I recommend using generator to make such a huge json.

About linter, karabiner_cli works as linter.
Distributed complex_modifications are checked by the linter.
https://github.com/pqrs-org/KE-complex_modifications/

For example, we can check `docs/json/personal_tekezo.json` in above repository by the following command.

```shell
'/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' \
  --lint-complex-modifications \
  docs/json/personal_tekezo.json
```

**Comment by dvdvdmt** [comment]
Thanks for your answers and especially for the handy linting command!

**Comment by dvdvdmt** [comment]
Thanks for your answers and especially for the handy linting command!

**Comment by mayeths** [comment]
I'm writing complex modifications with VSCode too because copy-pasting in the editor is easier than click-click-clicks in the generator for me. So after googling for `schemas/karabiner-14.3.json` or `schemas/karabiner-14.2.json` I found this issue. [Tool to generate JSON schema from JSON data](https://stackoverflow.com/a/30294535) may help, but still require some work for me to create a schema for karabiner.

It's a closed issue, but maybe there is a schema for karabiner some days? :)

**Comment by jbriales** [comment]
I came here also looking for a JSON schema, but then realized by looking more in depth into https://github.com/pqrs-org/KE-complex_modifications/ that you can just generate your JSON based on some basic JS code, and most existing modifications already do that, so they are easy to modify at the source code.

Still some autocompletion capabilities might be nice,
but for that we could maybe just extend https://github.com/pqrs-org/KE-complex_modifications/blob/main/src/lib/karabiner.js with more key definitions for autocompletion to work?

**Comment by chrisgrieser** [comment]
FWIW, [I created a JSON schema](https://github.com/chrisgrieser/.config/blob/main/%2Fkarabiner%2Fassets%2Fcomplex_modifications%2Fschema%2Fkarabiner-mod-schema.json) from my existing modification json files via [quicktype](https://github.com/glideapps/quicktype). It's not perfect, since I do not use all available karabiner features, but most use cases should be covered by it.

**Comment by notpushkin** [comment]
I've also created one: https://gitlab.com/notpushkin/karabiner-jsonschema
