### ISSUE TITLE
External Apple KB keys are mixed up when Karabiner's running

### ISSUE THREAD

**Issue by zakroma** [tekezo/Karabiner-Elements#192]
Hello!

I have an old apple keyboard A1048 (this one: http://xahlee.info/kbd/i2/Apple_pro_keyboard.jpg).
When Karabiner-Elements is running, MBP doesn't know that it's A1048 I'm using and thinks it's just an MBP kb.

When Karabiner-Elements is running upper row (F-keys) function not as they're designed to, but as MBP keys without Fn key being pressed (i.e. I can control brightness, backlit etc).

When Karabiner-Elements isn't running, keys function as they're designed to and every key corresponds to the icon on it (i.e. I can control the volume with the corresponding keys on the right side of the keyboard) and map F-keys to whatever I want. 

My config for Karabiner-Elements is CapsLock-related and has nothing to do with those keys. 

How do I make Karabiner only change my caps lock and leave all other keys as they are?

**Comment by maru3l** [comment]
I'm getting the same kind of issue with different key on my french canadien USB keyboard. When I'm plugging my external keyboard and I'm going to the keyboard visualisation in the Setting preferences, it is the compact keyboard of my laptop instead of my extended one.

I've tried to close Karabiner-elements and when I'm clicking on any key, the keyboard visualiser change for the right keyboard.

This is the log of my external keyboard:
```
[2016-09-29 11:45:52.022] [grabber] [info]   product: Apple Keyboard
[2016-09-29 11:45:52.022] [grabber] [info]   vendor_id: 0x5ac
[2016-09-29 11:45:52.022] [grabber] [info]   product_id: 0x250
[2016-09-29 11:45:52.022] [grabber] [info]   location_id: 0x14120000
[2016-09-29 11:45:52.022] [grabber] [info]   registry_entry_id: 4295135436
```

**Comment by ZhangBanger** [comment]
Can we put in a feature request for "Don't Remap Apple Keyboard" ? 👍

**Comment by rdmendo** [comment]
+1

**Comment by flodi** [comment]
+1 Italian Keyboard
http://f.fbrz.io/GAfP
