### ISSUE TITLE
Support for Microsoft Natural Keyboard 4000 Hotkeys. #703

### ISSUE THREAD

**Issue by tekezo** [tekezo/Karabiner-Elements#2]
https://github.com/tekezo/Karabiner/issues/703

**Comment by daviderickson** [comment]
Please please please add this!  My specific use case I'd like to accomplish is to press the 1 or 2 favorite keys and send Previous/Next directly to the Amazon Music app, which has no global shortcuts.

**Comment by jodylent** [comment]
Would love to see this feature! If there's anything that can be done by the community to help, let me know.

**Comment by NorbertKrupa** [comment]
As someone who is just moving to Apple for the first time, I desperately want all my 4000 keyboard functionality.

**Comment by amar-s** [comment]
Me, too! PLEASE!

This keyboard is the whole reason I started using Karabiner, and it was great replacement for the discontinued Mac drivers from Microsoft (Grrr…). I very much hope Karabiner-Elements re-gains this lost functionality, since there are many keys on this keyboard that are otherwise useless.

**Comment by johnwillsey** [comment]
I've got a few of the original microsoft ergonomic keyboards which have even more than the 4000, which I use today (because it's black vs white) and the older model has sleep, skip tracks and more.. If needed I can plug either in and generate any keycode debug you might need for the special keys.  Thanks

**Comment by decadent** [comment]
Btw, for anyone interested, you can assign some of the keys with [USB Overdrive](http://www.usboverdrive.com/) (which is not free, though you can use it in the nag mode). But even that program doesn't see the numbered favorites keys, so apparently there's something weird going on under the hood with this keyboard.

**Comment by dphov** [comment]
Someone figured out how to enable `Zoom` key?

**Comment by Erowlin** [comment]
The microsoft drivers aren't discontinued. As of today, I could use them. Here what I did: 
1- Uninstall any Intellipoint: Applications > Utilities and use both uninstaller for mouse and keyboard. 
2- Restart in recovery (CMD + R), you will need to disable the system integrity protection
    1- In recovery mode, get a terminal and hit `csrutil disable`
3- Restart in regular mode, install the latest version of Intellipoint https://www.microsoft.com/accessories/en-gb/d/intellimouse
4- Go to Preferences > Keyboard > Modifier Key > Select "Keyboard"
5- Change preferences as you like in the "Microsoft Keyboard" application
6- Restart again in recovery to re-enable csrutil: `csrutil enable`

Everything works for me except the "zoom", I can zoom in and zoom out, but I would prefer to be able to scroll on the page. Not able to do it as of now. Will keep posted here if I find some info.

**Comment by cantgis** [comment]
Me, too! PLEASE!

**Comment by noyannus** [comment]
-1 for the MS Natural 4000. 
Please, that would be sooo great!

@dphov 
Scrroll is possible, requires a bit of hex editor magic, see
https://scottbezek.blogspot.com/2012/02/remapping-zoom-on-microsoft-natural.html .
Personally, I'd use USBOverdrive for that, if KE won't do it.

**Comment by pioto** [comment]
I'm not sure how "developer hasn't had time to address this feature request" equates to "stale"...?

**Comment by Orangenhain** [comment]
By the way: https://github.com/Orangenhain/MS-Natural-Keyboard-HID-Handler still works, and can even co-exist with KE (tested on Mojave).

You just have to get it to start **before** KE. Since KE starts itself via system-wide LaunchD entries, the "easiest" way is probably having an AppleScript app running on account login that quits KE, starts the "Special Key Handler.app", and then (re-)starts KE (and gets rid of the resulting popup window).

**Comment by derekperkins** [comment]
Can we reopen this issue?

**Comment by wmcnamee-tunein** [comment]
Definitely not stale.

**Comment by DarkCloud14** [comment]
Yeah, is it possible to reopen this issue?

**Comment by noyannus** [comment]
Apparently nobody looks at a closed issue here.

Everybody who desparately wants this feature, open a new issue. And again and again, to show that there is a real need here.

**Comment by junoatscroll** [comment]
Commenting here to show interest. Has anyone gotten the extension keys working with macOS Catalina?

**Comment by Hackmodford** [comment]
I also would like this to be added.

**Comment by feigenblatt** [comment]
+1

**Comment by zecanard** [comment]
@tekezo Please reopen pretty please 🙏🏼

**Comment by frazierjason** [comment]
I also would like to use my Natural 4000 hotkeys.

**Comment by dioxide** [comment]
+1 for the MS Natural 4000.
Please, that would be sooo great!

The USB override ∧ MS-Natural-Keyboard-HID-Handler  do not work.

**Comment by g000m** [comment]
+1 this has been my favorite keyboard for over 10 years!

**Comment by ITJamie** [comment]
+1

**Comment by dioxide** [comment]
@tekezo Please reopen pretty please

**Comment by riotnrrd-eu** [comment]
Can we please re-open this issue?

**Comment by dsmurl** [comment]
+1, I have 4 of these keyboards and they fixed my carpal tunnel and avoided a bad surgery.  I just want the number buttons to work at the top of my favorites.
