### ISSUE TITLE
Conflicts with Amazon WorkSpaces

### ISSUE THREAD

**Issue by haochenx** [tekezo/Karabiner-Elements#203]
Thank you for the hard works making Karabiner compatible with macOS Sierra! It works perfectly for me except that it seems that Karabiner-Elements conflicts with Amazon WorkSpaces. Karabiner used to play very well with the WorkSpaces, but after I upgrade to Sierra and switch to Karabiner-Elements, I can no longer type in WorkSpaces. The current workaround for me is to quit Karabiner-Elements before connecting to my remote desktop.

Could you please help solving this problem? I'm glad to provide any debugging information if needed.

**Comment by haochenx** [comment]
Here's some hints that I found in Karabiner-Elements' log:

```
[2016-09-30 16:40:05.078] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
[2016-09-30 16:40:06.087] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
[2016-09-30 16:40:07.088] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
[2016-09-30 16:40:08.090] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
[2016-09-30 16:40:09.095] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
[2016-09-30 16:40:10.085] [grabber] [warning] There are pressed down keys in Apple Internal Keyboard / Trackpad. Please release them.
```

I'm getting those log entries while the WorkSpaces is connected.

**Comment by ybryan** [comment]
I also have this issue.

**Comment by chrisking** [comment]
Confirming this is a blocker as well.

Workspaces Version: 2.2.1.292 ( 10/13/16 )
Karabiner Elements Version: 0.90.68

I'm unable to corroborate @haochenx 's logs however I'll add that the trackpad / mouse operations are perfectly normal, only the keyboard is impacted.

If there are additional debugging steps I could perform please let me know.

**Comment by chrisking** [comment]
@tekezo this issue is still occurring, is there any other information I could provide that would help triage this?

**Comment by phunkfoo** [comment]
+1. Karabiner is an amazing piece of software. However, since upgrading to Karabiner-Elements *and* Sierra, the keyboard stops responding when in Amazon Workspaces. I can confirm that mouse and / or trackpad continue to operate normally - this only affects the keyboard (internal as well as external).

**Comment by pangeacake** [comment]
Maybe related to #447

**Comment by g12r** [comment]
This has been going on since before Elements and Sierra; pretty sure this is not a new issue to either Seil+Karabiner or the OS. One other set of notes: if Karabiner-Elements is running when I start Workspaces, I get no keyboard input inside the Workspaces host OS. Even if I quite K-E, Workspace keyboard inputs won't work. I have to restart Workspaces.

If I start Workspaces without K-E running, keyboard works inside Workspaces; then if I start K-E, keyboard stops working inside Workspaces; then if I quit K-E, keyboard resumes working. With this second scenario, I don't have to restart Workspaces to get the keyboard working again. It's not a workaround per se, but it is different behavior based upon which application was running first.

**Comment by jsharper** [comment]
With Karabiner 10.22 on El Capitan, the keyboard worked in Workspaces but the Karabiner mappings (Fn<->LControl swap in my case) were not in effect.  I just upgraded to Karabiner-Elements 11 yesterday, still on El Capitan, and now I am experiencing this issue - keyboard doesn't work at all in the WorkSpaces client.  Big bummer...

**Comment by scotttag** [comment]
Issue for me on High Sierra as well

Maybe an workaround option would be to have a program exclude list for Karabiner (and possibly others like Discord, according to the linked issue above) where it doesn't bind the keyboard into that program when it's running but carries on as normal with other programs, not sure if this is possible with the keybinding framework in macOS?

**Comment by toksvaeth** [comment]
Just counteracting the stale vacuum bot.  This is still an issue for me on High Sierra.

**Comment by jgspratt** [comment]
I was stuck with this issue for a while.  However, now, I am able to work around this issue by using an external keyboard and toggling the USB switch on my USB-C hub which corresponds to the keyboard.  I know this sounds really strange.  I was having a hard time reproducing the workaround because I couldn't figure out what order of events lead to me being able to use the keyboard and run Karabiner Elements.  But this seems to be it:

1. Connect Mac to USB hub
2. Log in to Workspace (keyboard does not work once inside Workspace)
3. Toggle power switch on USB hub (my hub has 4 ports and 4 power switches, so I toggle the one for the keyboard)
4. External keyboard now works (on board keyboard does not work)

I hope this helps someone.

**Comment by dgourlay** [comment]
If the issue still exists it should not be closed.

**Comment by toksvaeth** [comment]
FYI, On Karabiner 12.1.0 I do not appear to have this problem any more.

I can run Karabiner, open the Amazon workspaces client and -- huzzah -- type into the workspace.

**Comment by jsharper** [comment]
I'm not sure which change/upgrade resulted in the problem being resolved for me, but I can confirm that with macOS 10.13.6, Karabiner-Elements 12.1.0, and WorkSpaces client 2.4.9.837 (2018-08-29) I am no longer experiencing this problem.  Further, key remapping appears to be in effect!

**Comment by chrisking** [comment]
Confirming that 12.1.0 seems to fix it as well! This is a great day!!!

**Comment by ustun** [comment]
I have the same issue, but I don't know whether the culprit is Karabiner. I tried quitting Karabiner and it didn't work. The only fix was a restart, it sometimes works after a restart. The problem seems to be in Amazon Workspaces.
