### ISSUE TITLE
Support for the old ignore keyboard bouncing/chatter

### ISSUE THREAD

**Issue by brujoand** [tekezo/Karabiner-Elements#208]
`Karabiner core settings -> Advanced configurations -> Ignore bouncing/chattering events` It turns out this feature was the only reason my mechanical keyboard was usable. What needs to be in place to have this re-implemented? This is very useful to me so if some wage guidelines were given on how to implement it I'd be happy to give it a go.

**Comment by pmueller** [comment]
@brujoand @elanini We're in the same boat, my mechanical keyboard drives me crazy due to chatter without that `ignore chattering events` feature.

I made a small change on my fork to throw out key events that are too close together time-wise. It's a crappy hack with a hardcoded time value but it's working for my keyboard. If you want to try it you can [build my fork](https://github.com/pmueller/Karabiner-Elements) (should build with the normal instructions in the readme).

If you need to fine-tune it to work better with your keyboard you can adjust the time threshold here https://github.com/pmueller/Karabiner-Elements/blob/master/src/share/event_queue.hpp#L173

Hope this helps out for now

**Comment by pmueller** [comment]
Update for anyone still waiting for this feature to be included: This is a great little utility to fix keyboard chatter https://github.com/toothbrush/debounce-mac
I've been using it for a few weeks and rarely noticed any chattering.

**Comment by mutantcornholio** [comment]
can we reopen this? @tekezo 
this could be a fine software fix for new macbook keyboard problems

**Comment by Monkeyspit** [comment]
Works great!  It would be helpful if there were instructions for newbs like me.

**Comment by xcambar** [comment]
@tekezo I think we all understand this feature is not your priority, but considering a lot of people are willing to see this feature revived, can you share some pointers in the code where to start implementation?

My C++ skills are, to say the least, rusty, but I'd prefer to give this a shot instead of throwing my beloved keyboard and buy a new one. I need some guidance though.

Best 🙏 

---

@Monkeyspit I tried debounce-mac to no avail, how did you succeed?

**Comment by AhmedKorim** [comment]
hey any updates on this or alternatives

**Comment by ahmad-khan-educative** [comment]
Hi, are there any updates on this. My keyboard is driving me crazy.

**Comment by pinei** [comment]
Just found this problem in my mechanical keyboard too.

**Comment by n2iw** [comment]
I need this feature also!

**Comment by xpader** [comment]
Why there's a bot to close none activity issue? The problem is still there.
Keyboard debouncing/unchatter is a good things that lots of people need.

**Comment by matthewcarbone** [comment]
Still an issue for me but unrelated, I gotta say, it looks like @pmueller's solution with https://github.com/toothbrush/debounce-mac still seems to work 7 years later (for anyone still struggling with the problem)!
