### ISSUE TITLE
Impossible to replace , to . in keypad

### ISSUE THREAD

**Issue by Benji7790** [tekezo/Karabiner-Elements#298]
In previous version of Karabiner, i had an option to replace the "," touch of the keypad to ".". I can't find the way to do this with Karabiner-Elements.
macOS Sierra, french keyboard.

**Comment by rdmendo** [comment]
+1

**Comment by gjherbiet** [comment]
+1 as well.

In the meantime I used the following in BetterTouchTool but this creates a latency that make it unsuitable to quickly type e.g. IPv4 addresses (I end up with 1270.0..1 or 127.00.1 instead of 127.0.0.1).

![screen shot 2016-10-25 at 08 05 43](https://cloud.githubusercontent.com/assets/210227/19674687/036a4388-9a8a-11e6-9941-c295b2295a55.png)
