### ISSUE TITLE
Enabling scroll reverse in Karabiner-Elements through karabiner.json?

### ISSUE THREAD

**Issue by nhbean123** [tekezo/Karabiner-Elements#302]
Any tips on getting my logitech mouse to reverse the scrolling direction of my touchpad would be great. What code is needed in the karabiner.json file?

**Comment by brunojcm** [comment]
I would also really appreciate to know that!

**Comment by nathanielcook** [comment]
BetterTouchTool now has support for this with version 1.9.3

**Comment by nhbean123** [comment]
Thanks! Life-saving. Hopefully Karabiner is able to get this up soon enough but for now BTT will do great.

**Comment by brunojcm** [comment]
Using Logitech software as a workaround while Karabiner-Elements is not ready yet: http://apple.stackexchange.com/questions/116617/how-to-separate-mouse-and-trackpad-settings/259505#259505

**Comment by sjl2024** [comment]
Is there any update on this? I don't understand how long-time users of (reliant on) karabiner are suddenly without many of these critical features due to upgrading to Sierra. I really wouldn't have upgraded had I known this was going to be the case.

**Comment by alatar-** [comment]
+1

**Comment by byelims** [comment]
+1

**Comment by kongyuyu** [comment]
I think you might try scroll reverser, which can reverse mise scrolling while keep touchpad natural.

**Comment by carlsmith** [comment]
I use Scroll Reverser. It works perfectly.

**Comment by nowvisiting** [comment]
@nathanielcook Thank you! Didn't realize BetterTouchTool added that option. I've been using BTT since forever ago and am so happy to be able to rely on it fully now.

**Comment by craftey** [comment]
Scroll reverse is an important feature that I am missing from Karabiner Elements. I used the feature to reverse scrolling globally and selectively dis not reverse scrolling in certain apps like Quicktime or VLC because there reverse scrolling feels awkward when it comes to seeking video position or changing the volume with the touch pad.

The possibility to change scroll reverse app specific is missing from the mentioned alternative [Scroll Reverser](https://pilotmoon.com/scrollreverser). But Scroll Reversee at least allows me to reverse scrolling but having natural scrolling still active for desktop switching and mission control. That is better than globally switching natural scrolling off in MacOS trackpad settings.

Still missing the app specific version of Karabiner, though.

**Comment by leoatchina** [comment]
you can use free mac app https://github.com/Caldis/Mos instead

**Comment by skktce** [comment]
Any updates on thi

**Comment by carlsmith** [comment]
App-specific, scrolling directions would add another solid reason to install Karabiner. This should never have been closed.

**Comment by davidleejy** [comment]
Karabiner-Elements now lets users toggle the mouse scroll wheel direction independently of the trackpad's scroll direction. Additionally, I believe Karabiner can also independently modify each mice's scroll wheel direction.

Karabiner-Element settings > Devices > find the mouse device you want to affect > Enable "Modify events" > Enable "Flip mouse vertical wheel".

I checked that this works in Karabiner-Elements version 14.13.0.

**Comment by AntnPantnMantn** [comment]
+1
