### ISSUE TITLE
Does Karabiner Elements have support for Mouse Keys Mode v2 from Karabiner?

### ISSUE THREAD

**Issue by nikitavoloboev** [tekezo/Karabiner-Elements#307]

**Comment by thaibui** [comment]
👍 I rely on this mode heavily and the new mac sierra sucks because i don't have it :(

**Comment by LynnWalton** [comment]
👍   I desperately need this functionality to.

**Comment by LynnWalton** [comment]
Does anyone know how to do it with hammerspoon?

**Comment by tekezo** [comment]
Mouse keys are available since the latest beta version.
You can use them from complex_modifications.
https://pqrs.org/osx/karabiner/complex_modifications/#mouse_keys_simple

How to upgrade to the latest beta version:
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by nikitavoloboev** [comment]
Thank you @tekezo 🎊 

Only [launcher mode](https://gist.github.com/nikitavoloboev/b591b290c6a55ac47b19158c721415a4) and simultaneous keys left. And I can finally upgrade to Karabiner Elements. 🙂

**Comment by LynnWalton** [comment]
Yes, big thanks @tekezo.  I'm very thankful for this, on this thanksgiving weekend in the U.S.  I got this notice about mousemode v2 within one hour of getting my new macbook (which I'd been delaying for almost a year and a half, all because I didn't want to do without Karabiner elements).    Great timing! :)
