### ISSUE TITLE
External Keyboard Brightness Keys Adjust Incorrect Screen

### ISSUE THREAD

**Issue by tylerb** [tekezo/Karabiner-Elements#327]
Greetings!

Thanks for this product and continued development. It makes my life much better.

On my MBP, when an external cinema display is plugged in and an external keyboard is in use, the F1 and F2 (brightness keys) on the external keyboard will adjust the brightness on the external screen. The F1 and F2 keys on the laptop keyboard will adjust the brightness on the laptop screen.

If Karabiner-Elements is running, the brightness keys on the external keyboard adjust the brightness on the laptop screen instead of the external screen.

**Comment by chrisfsmith** [comment]
I also have this problem.

FYI you can use Control-F1 and Control-F2 to adjust the cinema (thunderbolt) display's brightness. Control-F1 and Control-F2 are suppose to adjust the brightness of a second external display.

**Comment by jimryan** [comment]
I have this problem as well.  Thanks for the Control+F1/F2 tip.  I can at least adjust my first cinema display with that.  I'm unable to adjust my second cinema display, though, since that's what Control+F1/F2 is supposed to do. 

I happen to use my MBP in clamshell mode, but I could see how mapping keys that adjust the brightness of the MBP display could be useful for those who don't.  I'd love to see this as an option, or it'd be even better if it could figure out what to do automatically based on if the Macbook is in clamshell mode or not.  Either way, I'm fine if in the end I have to use a modifier, but it'd be swell if I could have some way to adjust the brightness of my second cinema display.

**Comment by brtdv** [comment]
To anyone coming here in 2020: this bug still exists. For me, the CTRL+F1/F2 is a great workaround I was not aware of.
