### ISSUE TITLE
Backtick and § are swapped

### ISSUE THREAD

**Issue by m4rkw** [tekezo/Karabiner-Elements#345]
Just built and installed from github, it seems that backtick and § are swapped by default and I can't see how to swap them back.

What I'd really like to do is map § to escape to deal with the upcoming changes to the Macbook Pros, is that possible to do?  I couldn't see any way to do it via the GUI so I'm guessing it'd need manual plist changes.

Thanks

**Comment by reboot81** [comment]
I believe the keyboard is detected wrong, and not a mapping problem.
Open System preferences, Keyboard, Input. See that the physical layout is different?
Somehow macOS detects an ANSI keyboard, even though it's an ISO layout.

Uninstalling Karabiner will return the layout to ISO.

**Comment by m4rkw** [comment]
Weird.  in any case I figured out how to remap the keys now so all good.

**Comment by reboot81** [comment]
@m4rkw Oh you did? Care to share your solution?

**Comment by m4rkw** [comment]
"simple_modifications" : {
				"non_us_backslash": "grave_accent_and_tilde",
				"grave_accent_and_tilde" : "escape"
      },

**Comment by andruby** [comment]
I seem to have the same issue. I have a macbook pro touchbar with ISO dutch qwerty keyboard. I remapped the original §± key to esc, and now the grave_accent_and_tilde key produces §±.

This has happened only since upgrading Karabiner Elements to 11.3.0. It didn't happen in the earlier versions where I didn't have to pick a keyboard layout in Karabiner Elements.

My Mac preference keyboard -> input source shows dutch qwerty.

When I choose "Keyboard type: ANSI" in Karabiners Virtual Keyboard everything is ok. I've use this as a workaround.

**Comment by adamcharnock** [comment]
I'm having the same issue as @andruby, with a British English keyboard layout.

**Comment by smohammadhn** [comment]
This solved my problem. Selecting ANSI instead of ISO


---------
![image](https://github.com/user-attachments/assets/f2c307dd-2958-4507-b15d-35ba5640af0a)
