### ISSUE TITLE
From and to: ?

### ISSUE THREAD

**Issue by rnbarg** [tekezo/Karabiner-Elements#348]
This may seem obvious but counterintuitive

From: Left Control -> To: Function  - I would have expected that the Function key would now do what the Left Control key does, but it turns out to be the opposite. 

It appears it works this way: Simple key modification (change key "left control" to another key Function)   This doesn't make intuitive sense to me.

**Comment by cormacrelf** [comment]
**From** is the event normally sent by the physical key you type. **To** is the event it becomes. Your keyboard is an input, sending events in a single direction, from your keyboard -> to your computer. Karabiner-Elements transforms this input: it takes 'from' events and transforms them into 'to' events. What could possibly make more intuitive sense than that?

Close this issue if you understand; even if you don't, close it anyway because it seems to make sense to everyone else.
