### ISSUE TITLE
macOS 10.12.2 Beta breaks keyboard completely

### ISSUE THREAD

**Issue by AdrianLoer** [tekezo/Karabiner-Elements#383]
FYI:
I Installed the newest beta 10.12.2 and the keyboard is totally broken after user log in.
Found Karabiner-Elements to be the problem after some trial and error

**Comment by th507** [comment]
Same here. Uninstalling Karabiner-Elements solves this issue.

**Comment by tekezo** [comment]
I confirmed this issue.
It's macOS issue that `IOHIDPostEvent` API is totally broken in 10.12.2.
I hope the macOS issue will be fixed since release.

**Comment by GhostValk** [comment]
Same here, gotta quit Karabiner every time i restart.

**Comment by talha131** [comment]
Just installed 10.12.2 Beta (16C32f). API hasn't been fixed yet.

**Comment by Y-knot** [comment]
Same here. 
Any idea which files need to be restored from Time Machine in order to bring this IOHIDPostEvent API to previous version? (If that's possible at all.)

Would be nice to have some way of notifying KE users to hold back from a certain macOS version.

**Comment by john-denisov** [comment]
10.12.2 Beta (16C32f). Had a 2 seconds time window to enter my password on login screen. Then keyboard stops working. Solved by completely removing Karabiner

**Comment by GhostValk** [comment]
I can input my password without problems at the login screen, but after it, the keyboard stops working. It's not neccesary to remove it, just open K-E ant quit it (Option in the first tab)

**Comment by eugenesvk** [comment]
As an alternative quick fix - you can open Karabiner-Elements with a mouse and then uncheck your keyboard in the **Devices** section and just wait for an K-E autoupdate to fix this rather surprising issue

**Comment by manojfedx** [comment]
Guys I uninstalled Sierra 10.12,2 and again installed fresh Sierra 10.12.1 from store! When is 10.12,2 officially going to come??

**Comment by austinmao** [comment]
👍

**Comment by albohlabs** [comment]
With the new macOS Update it seems to work.

**Comment by talha131** [comment]
Karabiner-Elements is working on `10.12.2 Beta (16C41b)`.

**Comment by saagarjha** [comment]
PSA: for those of you who are trying to reinstall, but can't because [pqrs.org](pqrs.org) is down, the installer is conveniently located [here](https://github.com/tekezo/pqrs.org/blob/master/webroot/osx/karabiner/files/Karabiner-Elements-0.90.64.dmg).

**Comment by abruzzihraig** [comment]
@talha131 Seems it doesn't work on 10.12.2 Beta (16C32f)?

**Comment by talha131** [comment]
@abruzzihraig yeah, it does not work on `16C32f`. https://github.com/tekezo/Karabiner-Elements/issues/383#issuecomment-258190405

You need to update to `16C41b`.

**Comment by jspiro** [comment]
Confirmed that it's fixed in the latest OS beta. This should be closed.

**Comment by sprig** [comment]
Does anyone know how to force the app store to show this update? So far I'm stuck on 16C32f.

**Comment by jspiro** [comment]
Restart and try another internet connection. More likely Apple is seeding it to a percentage of users before making it generally available.

**Comment by jspiro** [comment]
Just curious if anyone knows WHY it was broken in that build?

**Comment by sprig** [comment]
@jspiro thanks for the suggestion, but I already tried that and was hoping for something deterministic with a proven result, rather than some fiddling voodo based on (reasonable, I agree) assumptions on how apple operates.

What did work for me, if anyone has the same problem, (though I don't know whether that is deterministic either) was to change from the beta update channel to the developer channel.
Instructions available here: https://pikeralpha.wordpress.com/2016/06/08/catalogurl-for-os-x-10-12/

**Comment by gAmUssA** [comment]
fixed in the latest OSX beta

```
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C41b
KE 0.90.64
```

**Comment by tekezo** [comment]
16C41b seems has a important security hole.
I recommend you to do not use the beta version for daily use.

**Comment by talha131** [comment]
@tekezo Can you please point me to the link where I can read more about this security hole?

**Comment by tekezo** [comment]
I've filed a bug report to Apple about this security hole.
I can publish that security hole after it has been fixed.

**Comment by sprig** [comment]
Can you at least state how bad it is? on the scale of automated remote root to local escalation to info leaking?

**Comment by manojfedx** [comment]
Im using wireless mouse. For smooth usage I run Smooth scroll app. After 10.12.2 beta my smoothsccroll became dead along with Karabiner. So I had to go back to 10.12.1!
Now can I install 10.12.2 so that my smooth scroll  and Karabiner both will work?
PS : Cant survive without smooth scroll and karabiner!

**Comment by tekezo** [comment]
I've confirmed the security issue of macOS 10.12.2 has been fixed in 16C60b.

The security issue was any processes can observe your keyboard input in the password prompt by using IOHIDDeviceRegisterInputReportCallback.

Example Code:
https://github.com/tekezo/Karabiner-VirtualHIDDevice/blob/master/appendix/dump_hid_report/main.cpp

**Comment by willin** [comment]
16C67 not fiexed
