### ISSUE TITLE
Neo2 Fixes

### ISSUE THREAD

**Issue by christophebeling** [tekezo/Karabiner-Elements#40]
I would like to use karabiner to configure neo2 for macOS sierra. Unfortunately i can not find the config options for the json. http://wiki.neo-layout.org/wiki/Neo%20auf%20dem%20Apple%20Macintosh%20einrichten

Any help would be highly appreciated.

**Comment by neominik** [comment]
I am trying to port the old neo2 configuration to json too.
Unfortunately there are still some features missing here.
It can map from one key to another atm.
This is not enough to map the 4th and 6th layer.

**Comment by pfitz** [comment]
Really would like to see better and more complex examples and/or a reference to make more complex configs.

**Comment by pfitz** [comment]
@neominik I tried this config and it does nothing for me. how did you installed it

**Comment by nonec** [comment]
This works fine for me: 
```json
{
    "profiles": [
        {
            "name": "Neo Layout",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_option",
                "non_us_pound": "right_option"
            }
        }
    ]
}
```

**Comment by PaulePan** [comment]
I hope that there will be a solution for Layer 4/6. I think we have to wait for final Version of Karabiner Elements.

**Comment by fabyeah** [comment]
Level 4 isn't working yet, is it? :(

Or has anyone managed to make it work? Is there a workaround or another tool to achieve this?

**Comment by tjanson** [comment]
Nope, not to my knowledge. I (painfully) rolled back to El Capitan via Time
Machine to get Neo again.

This is really quite an important issue for Neo users on Mac OS and should
be discussed in the Neo project. Unfortunately their website and issue
tracker seems somewhat abandoned, at least to me (being used to fairly
quick reaction times on GitHub).
It definitely would be a good idea to put a warning on the Neo website/wiki
to warn users not to upgrade (though it might be too late by now).

**Comment by alteroppa** [comment]
+1

**Comment by SirVer** [comment]
+1 - I would like to support this somehow, preferably with money. Can I donate somewhere to give this bug priority?

**Comment by jgosmann** [comment]
I'm working on a implementation of the Neo2 layout [over here](https://github.com/jgosmann/Karabiner-Elements-Neo). Actually I'm mostly finished on the implementation side, I just have to do some more testing and add some installation instructions. Unfortunately, you will have to compile (and sign) that version yourself right now because I don't have an Apple Developer account that would allow me to create a redistributable package.

**Comment by SirVer** [comment]
@jgosmann That is very awesome! Will this be merged back into the main repo? How can I help testing this?

**Comment by jgosmann** [comment]
I have no plans at the moment to get this in a state where it would be merged back into the main repo. Many of the layer 4 keys are hard coded which would not be acceptable in the main release.

As for testing: Install it and see if the layout including layer 4/6 works? (I haven't written the compile and install documentation yet, hopefully I manage this weekend.)

**Comment by SirVer** [comment]
@jgosmann Could you ping this bug once you have outlined the installation process somewhere? I have for example no experience to sign a kernel extension, so I would not know how to install this.

Also, could you write a few lines of what cleanup would be needed to get this merged back into master? It would be a shame if you effectively fork this and people in the future would need to choose between your Neo port (which probably did not receive latest bug fixes since you moved on) and upstream. Not suggesting that you should do the cleanups (you did plenty by making Neo work!), but only you know what would be required. So writing something down gives somebody else a chance to do the work.

**Comment by jgosmann** [comment]
> Could you ping this bug once you have outlined the installation process somewhere?

Will do.

> Also, could you write a few lines of what cleanup would be needed to get this merged back into master?

I think the main part would be a way to to allow to configure remappings from a key + a set of modifier key to a different key + a different set of modifier keys. Then the Neo2 remappings need to be moved from the source code to that config file. Probably is is also necessary to do some cleanup of the actual code doing the remapping; it is a little bit hacked in now (partially because I'm not really familiar with the code base).

**Comment by SirVer** [comment]
Cool, thanks. I will wait for your installation guidance and then test this.

**Comment by jgosmann** [comment]
I've put the [installation](https://github.com/jgosmann/Karabiner-Elements-Neo/blob/neo2-layer4/README.md) and [build](https://github.com/jgosmann/Karabiner-Elements-Neo/wiki/How-to-build-Karabiner-Elements-Neo) instructions online. Please test them and let me know if anything doesn't work or I skipped something.

**Comment by christophebeling** [comment]
well, for building this you need an apple developer license wich costs 99 $ per year, don't you? can anyone here maybe upload a compiled version?

**Comment by jgosmann** [comment]
You don't need a developer license if you build and run it on your own Mac. You only need the developer license if you want to distribute the build package and have it run on other people's Macs. That's why I can't distribute a compiled version at the moment.

**Comment by SirVer** [comment]
@jgosmann Thank you for putting the documentation up. I tried following the build instructions, but in step 3

> Click the “Create” buttons next to “Developer ID Application” and “Developer ID Installer”

Those buttons are greyed out for me. The only things I can "create" is `iOs Development` and `Mac development`. Is this expected? How can I change this?

Otherwise, the build seems to have been successful, beside the signing of course. Full output [is in this gist](https://gist.github.com/SirVer/ddcd707e255f9b1409e4413a118b87a3).

**Comment by jgosmann** [comment]
I might have remembered incorrectly which buttons I clicked. Can you try the “create” button next to “Mac development”?

> Otherwise, the build seems to have been successful, beside the signing of course.

Unfortunately, I don't think the required kernel module will be loaded without being signed.

**Comment by SirVer** [comment]
Partial success here. It seems that it properly codesigns the binaries, but not the package:

~~~
code sign Library/Application Support/org.pqrs/Karabiner-Elements/updater/Karabiner-Elements.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app
code sign Library/Application Support/org.pqrs/Karabiner-Elements/updater/Karabiner-Elements.app
code sign Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber
code sign Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_event_dispatcher
code sign Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_console_user_server
code sign Applications/Karabiner-EventViewer.app
code sign Applications/Karabiner-Elements.app
~~~

but later

~~~
Sign with Developer ID
productsign: error: Could not find appropriate signing identity for “D497CAAC851FC0B463D7D33B87D09CF169C6B3CD”.
Make Archive
~~~

Full output: https://gist.github.com/SirVer/ddcd707e255f9b1409e4413a118b87a3

I will try to install this tomorrow. @jgosmann, Any more ideas on the package codesign error?

**Comment by jgosmann** [comment]
There will remain some elements that cannot be signed which is fine. However, in your case nothing seems to be signed as there is the following error multiple times:
```
D497CAAC851FC0B463D7D33B87D09CF169C6B3CD: no identity found
```
I think you missed [step 4 of the build instructions](https://github.com/jgosmann/Karabiner-Elements-Neo/wiki/How-to-build-Karabiner-Elements-Neo#build) because the ID is my the one of my key.

**Comment by SirVer** [comment]
@jgosmann My apologizes, I relinked the first gist again. I am not having my best day today :/. The correct one is https://gist.github.com/SirVer/1be4e5c16284b8b53931ac92eba8ffc4.

**Comment by jgosmann** [comment]
I think that might be fine. It seems only the installer could not be signed which should be ok (as long as you don't want to distribute it to other people). So I'd suggest to install it and see if it works.

**Comment by SirVer** [comment]
The package did install without any problems and the other layers are working on my laptop again. I will upgrade my Mac now from El Capitan and see if it still works. I will report any further issues in this bug.

@jgosmann Your build instructions and installation information are correct and working. Thanks again for putting this together.

@christophebeling I can confirm that no payed developer license is needed for the instructions.

@tekezo Neo2 is a popular keymap in Germany and having it supported will benefit karabiner-elements popularity. Could you offer your opinions on upstreaming Jan's changes into the master branch?

**Comment by jgosmann** [comment]
> @jgosmann Your build instructions and installation information are correct and working. Thanks again for putting this together.

Just to verify: Did you end up clicking the “Create” button next to “Mac development”? Also, it just occurred to me that the other buttons might have been greyed out because the corresponding signing keys were already generated.

**Comment by tjanson** [comment]
I can confirm that it builds fine using a key created with ”Mac Development” (the other option was greyed out for me too — [possibly due to this](https://stackoverflow.com/questions/39415871/xcode-cant-create-developer-id-application-button-greyed-out), but it doesn’t seem important).

After trying it for a few minutes, the only odd thing I notice is `Home/Pos 1` & `End` (i.e., Mod4+U/E (Neo) = Mod4+A/F (Qwertz labels)), which seems to behave differently in different contexts/applications (e.g., in this text box, it scrolls up and down). I’ll open an issue for that.

(Also: re-adjust the key repeat settings to something sane like 250 / 50.)

Thank you very much @jgosmann! Maybe I’ll dare to update to Sierra after all. ;)

**Comment by SirVer** [comment]
@jgosmann First issues I encountered:

-  CapsLock/Right Cmd + Qwerty-A used to jump to the beginning of the line, but now instead scrolls up.
- CapsLock/Right Cmd + qwerty-asdf are the cursor keys. But adding shift to select text does not work, but did before.

**Comment by jgosmann** [comment]
I think it would be best to post such issues to the [jgosmann/Karabiner-Elements-Neo issue tracker](https://github.com/jgosmann/Karabiner-Elements-Neo/issues) and discuss them there. I just noticed that the issues tab was deactivated, but I enabled it now. I also added the problems mentioned as jgosmann/Karabiner-Elements-Neo#1 and jgosmann/Karabiner-Elements-Neo#2. I will fix them as soon as I have time.
