### ISSUE TITLE
Disable NonBreaking Space

### ISSUE THREAD

**Issue by unixhelden** [tekezo/Karabiner-Elements#412]
Can you please bring back the ability to disable the non breakable space implementation? 

Please, Please, Please :)

**Comment by lichtamberg** [comment]
Yeah please, this is the only reason why I install karabiner... Sad that its not included

**Comment by kamykaze** [comment]
The old Karabiner had a lot of mappings. Can you be more specific of what this does?

**Comment by lichtamberg** [comment]
Accidentially pressing Option + Space keys are creating a non-breaking space - not a normal breaking space, which leads to corrupt commands in the end because they are not recognized.
See here the stack overflow answer, there is also one for the old keyremape4macbook: https://superuser.com/questions/78245/how-to-disable-the-option-space-key-combination-for-non-breaking-spaces

**Comment by kamykaze** [comment]
Ok, so it's basically changing Alt+Space to Space, and Alt+Shift+Space to Space

**Comment by lichtamberg** [comment]
correct :)

**Comment by kamykaze** [comment]
Ok, please follow the issue on the KE-complex_modifications repo. Someone please close this issue.
