### ISSUE TITLE
I can't remap a key to "underscore"

### ISSUE THREAD

**Issue by Farzy** [tekezo/Karabiner-Elements#428]
I use a TypeMatrix keyboard with a french «bépo» mapping. On this keyboard the underscore "_" is Alt+Space.

On some environments (a VM under Parallels for example) it doesn't work. Therefore I'd like to remap an unused key to "_".

I can't find a way to use simple mapping to do this as "underscore" does appear in the drop-down list. How can I do this? Is this a feature not implemented yet?

**Comment by kurko** [comment]
I cannot find how to that either. In my case, I just want Right Command to be mapped to Underscore. I tried to map Right Command to Shift and to Minus at the same time (as Shift+Minus = Underscore), but that didn't work.

**Comment by GlowingApple** [comment]
I am trying to do something similar.  I want to map caps lock directly to underscore.  Since an underscore is really shift+hyphen, a complex modification is required.  I can't figure out any way to add my own complex modification in the app, or submit a file to the website... 

But I was able to create a complex modification in `~/.config/karabiner/assets/complex_modifications/underscore_mapping.json` to do my mapping.  I've included the file, and @kurko I also included your right command mapping.

Download, unzip the file, and move to `~/.config/karabiner/assets/complex_modifications/`.  Open the app, click on the Complex Modifications tab, click on Add rule, select the rule in the list (it should be there now) and click Enable.

[underscore_mapping.json.zip](https://github.com/tekezo/Karabiner-Elements/files/1228608/underscore_mapping.json.zip)

**Comment by techana** [comment]
Apple arabic input source has a bug. It types kashida (ـ) instead of underscore (_) when pressing on shift+hyphen keys!

I'm trying to solve this bug using KE but without any success. I hope KE can add "underscore" key code to the codes list. Alternatively, it may allow entering text or unicode code in the "to" modifier.
