### ISSUE TITLE
Volume keys not work with Karabiner-Elements and Logitech k760

### ISSUE THREAD

**Issue by mrScalder** [tekezo/Karabiner-Elements#458]
OS X version: OS X 10.12.1
Karabiner version: Karabiner-Elements 0.90.67
Your Mac hardware: MacBook Pro 13 (Early 2011)
Your keyboard hardware: Logitech k760

Enabled "use all F1, F2, etc. keys as standard keys" in system preferences and karabiner-elements (0.90.67).
Standart f10-f12 keys work fine, but fn+f10-f12 not work.
In EventViewer fn+volume keys not shows.

Standart keyboard (macbook pro) works fine.
When deselect option "use all F1, F2, etc. keys as standard keys" in karabiner-elements - volume keys works without fn modifier.

**Comment by Polishapple** [comment]
On my keyboard volume control (separate buttons) also aren't working when karabiner is on.

**Comment by Username-Bacon** [comment]
Volumes keys and eject key on my keyboard does not work on my original apple wireless keyboard.

**Comment by reesd** [comment]
With K760 once Karabiner Elements is started the Karabiner Event viewer doesn't see any function keys or Eject.

**Comment by Logoth** [comment]
Similar issue on a Logitech G710+. The volume roller, mute button, and dedicated media keys stop functioning, and are not detected by the Karabiner Event Viewer if Karabiner Elements is running.

**Comment by cdelaet** [comment]
Similar issue on K780. On Mac OS media keys and Fn keys are swapped around in Karabiner. Furthermore, the keys are mapped to different keys than the markings on the keyboard.

**Comment by ericchang00** [comment]
Same issue with the volume roller and media controls on Logitech G810

**Comment by studgeek** [comment]
Note, I was incorrect in my previous comment. On K760 regular function keys work, but volume/media keys do not.

**Comment by awdensmore** [comment]
Similar issue on K270 - top media keys (play/pause, volume up/down, etc) don't register with EventViewer. All other keys seem to register fine. Once Elements is turned off, the media keys work again.

**Comment by samuellinde** [comment]
Event Viewer still doesn't log any fn presses.

**Comment by khit** [comment]
I've had the same issue with my Logitech keyboard. I also have a Logitech mouse and while I'd like to use Logitech Options to customize both, its not worth it to me since it interferes with Karabiner-Elements. (**Gotta** have Caps Lock working the way I want but I don't want to lose ALL the function/media keys which seems happen when I have Options installed.) Since this doesn't seem to be going away, my workaround was uninstalling Options and using Karabiner to customize things. Without Options installed you get key events from every key and go from there. Not ideal but better than having a row of useless keys at the top of my keyboard...
