### ISSUE TITLE
Shift+Delete to forward delete

### ISSUE THREAD

**Issue by blahster** [tekezo/Karabiner-Elements#528]
Is it possible to have combinations?
For example,
`left_shift + delete_or_backspace` to `delete_forward`

**Comment by megclaypool** [comment]
I would also like to be able to do this -- now that I'm back in the US with the American keyboard I'm used to, shift+delete = delete_forward is the main reason I need Karabiner. NEED. Not being able to forward delete is driving me nuts :(

Also, to add on to the original question, is it possible to specify shift as a modifier key without specifying left or right, or would I need to make two definitions, one for left_shift + backspace = delete_forward and a second for right_shift + backspace = delete_forward?

**Comment by printercu** [comment]
I found the easiest way for me is to switch to BetterTouchTool. It seems to be an overkill, while i'm using it only for this single feature. But I hope karabeiner will be able to handle keys combinations before my BTT trial exceeds :)

**Comment by megclaypool** [comment]
Ugh -- my BTT trial is expiring in one more day... Any progress on shift+delete to forward delete?

**Comment by megclaypool** [comment]
### Woohoo -- I've found my solution!

So, here's one way to get shift+delete => forward delete working in Karabiner Elements:

All of the settings in Karabiner Elements are stored in a preference file at ~/.config/karabiner/karabiner.json. As you make changes in your Karabiner Elements settings, fancy codes get printed in the file. I imported a couple of rules and looked at them in the json file and was able to cobble together my own rule that successfully causes shift+delete to forward delete! Unfortunately I can't figure out how to export my rule. So, assuming you don't have many preferences set, or you're willing to recreate them, you can go to your terminal and type (or paste) `open ~/.config/karabiner/karabiner.json` and replace the contents with the following:

```
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": false,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.to_if_alone_timeout_milliseconds": 1000
                },
                "rules": [
                    {
                        "description": "Change shift+delete to forward delete",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "delete_or_backspace",
                                    "modifiers": {
                                        "mandatory": [
                                            "shift"
                                        ],
                                        "optional": [
                                            "caps_lock"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "delete_forward"
                                    },
                                    {
                                        "key_code": "vk_none"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "devices": [],
            "fn_function_keys": {
                "f1": "display_brightness_decrement",
                "f10": "mute",
                "f11": "volume_decrement",
                "f12": "volume_increment",
                "f2": "display_brightness_increment",
                "f3": "mission_control",
                "f4": "launchpad",
                "f5": "illumination_decrement",
                "f6": "illumination_increment",
                "f7": "rewind",
                "f8": "play_or_pause",
                "f9": "fastforward"
            },
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {},
            "virtual_hid_keyboard": {
                "caps_lock_delay_milliseconds": 0,
                "keyboard_type": "ansi"
            }
        }
    ]
}

```
Then save the file. Voila, you too will be able to forward delete once more!

# Big Disclaimer!!!
This will entirely replace all of your Karabiner Elements settings with this one shift+delete = forward delete rule. Which, since that's basically the only thing I'm using Karabiner Elements for, would have been totally acceptable to me. But if you go this route and you have other settings, you'll have to recreate them. If you're willing to get a little hacky, you could do what I did and look at the code and copy and paste my extra/different stuff into your existing file without deleting what you've currently got. If you make a backup of your current json file, you can experiment a bit and if it all goes pear shaped, you can just paste your original settings back and at least be no worst off than you started :)

**Comment by blahster** [comment]
This was solved with complex modifications - https://pqrs.org/osx/karabiner/complex_modifications/#delete

**Comment by kodmanyagha** [comment]
```json
{
    "description": "shift+backspace to delete",
    "manipulators": [
        {
            "from": {
                "key_code": "delete_or_backspace",
                "modifiers": { "mandatory": ["right_shift"] }
            },
            "to": [{ "key_code": "delete_forward" }],
            "type": "basic"
        }
    ]
}
```
