### ISSUE TITLE
Turning off Karabiner-Elements kills m,jkio keys

### ISSUE THREAD

**Issue by dabro** [tekezo/Karabiner-Elements#529]
0.90.72
Sierra 10.12.2 on Macbook 2012 15" Retina

Also, the simple modifications don't stick between restarts, and don't work.
Adding the karabiner.json file manually works.  Maybe 0.90.72 is writing to old location and reading from ~/.config/karabiner/karabiner.json ?

Removing the driver/uninstalling also kills those keys.

Happy New Year!

**Comment by wwwdata** [comment]
I also wanted to uninstall karabiner and am facing the same problem that the keys you mentioned aren't working anymore. Luckily my external keyboard is working... Even when booting up in safe mode those keys stay broken on the internal keyboard. How to remove everything that karabiner elements changed?

**Comment by wwwdata** [comment]
when I reinstall my old 0.90.36 version and let that upgrade i can at least use my internal keyboard again but when running the uninstall.sh script its broken again ... so at least i can use my keyboard without reinstalling... but can anybody explain what exactly to remove in order to completely get rid of karabiner?

**Comment by wwwdata** [comment]
So when karabiner is uninstalled/disabled and I create a new user and log in with that user, the `m,jkio` keys are working for that user. Only when logging back in with my main they stay broken until i reinstall karabiner elements and activate it for the build in keyboard... So I guess it must have somehow overwritten some keyboard mapping settings in my user profile?

Which means the keyboard is in a broken state but because karabiner captures all the input events, it somehow "fixes" it when its running...

Where do I look for those settings? How to just restore the default settings like they are for the newly created user? Can anybody please help?
