### ISSUE TITLE
Function keys switch?

### ISSUE THREAD

**Issue by ticofab** [tekezo/Karabiner-Elements#537]
My absolute favourite feature used to be the "fn+ESC" combo to switch functional keys from the default functions (volume up/down, brightness etc) to the actual F1...F12 functionalities. 
Is it possible to do this or are you guys going to implement it at some point?
Thanks for all your invaluable work!

**Comment by ticofab** [comment]
For those interested, as a workaround I am using an [Alfred Workflow](https://github.com/riyaz/alfred-workflows/tree/master/Toggle_Fn_keys_as_standard_keys).

**Comment by akaralar** [comment]
it would be great if the fn switch could be specified in the json, so that it can be changed with profiles

**Comment by LorenzoCampanella** [comment]
Many thanks for your answer.
I don’t want to use another app because I fear a conflict between apps. I had already a conflict in the use of Fn keys between Karabiner and Battle.net<http://Battle.net>,  where I need the Fn keys in normal F1, F2, F3 use.
Actually, I solved the problem creating alternative keys on Battle.net<http://Battle.net>.

I would prefer if karabiner did both things: change keyboard map and fn keys when changing profile…
Many thanks again for your interest

Il giorno 07 set 2018, alle ore 01:24, Ahmet Karalar <notifications@github.com<mailto:notifications@github.com>> ha scritto:


FWIW, I ended up using https://github.com/Pyroh/Fluor to switch my fn keys and karabiner for other things. Maybe this will help someone.
