### ISSUE TITLE
Eject key not working on Apple external keyboard + Swapped keys (`~ with §±)

### ISSUE THREAD

**Issue by gabijguma** [tekezo/Karabiner-Elements#544]
Hey there, 

It seems that Karabiner-Elements is messing with the Eject key on the external apple keyboard, rendering it pretty unusable.

Also, the following keys are swapped (`~ with §±), making cycling thru windows a not so swell experience :)

Any solutions for that?

MacOS Sierra
MacBookPro with Apple keyboard, US layout

Thanks.

**Comment by pawelphilipczyk** [comment]
This is like the most useful feature and it's missing!

**Comment by jabbrwcky** [comment]
Haven't tried the Power-Key on the external Keyboard but I can confirm the same swapping effect.

In my case the cause is that apparently the internal Keyboard (MBP with EU US-Kbd layout) seems only to work correctly when I set the Virtual keyboard to ANSI - the external Keyboard OTOH only works if I set the Virtual Keyboard to ISO.

**Comment by gabijguma** [comment]
Any news on this?

**Comment by jorvi** [comment]
See https://github.com/tekezo/Karabiner-Elements/issues/46
