### ISSUE TITLE
"Help" key remapping broken

### ISSUE THREAD

**Issue by bcbishop** [tekezo/Karabiner-Elements#566]
Hi @tekezo - thank you so much for your hard work in making Karabiner, and now Karabiner Elements. Your work is indispensable.

I've had a problem remapping the "Help" key. Per Events Viewer, Karabiner Elements is recognizing the keypress, but none of the remap settings actually work. (It still shows up as "Help".)

I've tested this across two different keyboards, but realize there may be something I'm missing. Thanks for the assist!

**Comment by bcbishop** [comment]
Bumping this to see if anyone has any ideas. Only thing I can think of is that it's related to the Fn flag (screencap below). Thanks!
![screen shot 2017-03-01 at 7 28 40 am](https://cloud.githubusercontent.com/assets/21987263/23466822/049d9c70-fe51-11e6-9c79-70671b091357.png)

**Comment by goodtouch** [comment]
While It seems that you can't remap the `help` key directly, you can still remap actions with it, but not by using the `help` key_code.

For example with a TypeMatrix keyboard, when you press the copy or paste special commands, it shows up as `help+[some modifiers]` in EventViewer but you have to use the `insert` keycode to remap them. (I don't know if this is due to some specific code to handle copy & paste in Karabiner though, but maybe it can help...)

You can look at https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/typematrix_bepo_cut_copy_paste_fn_shortcuts.json to see how they are remapped :

- `help+left_control` (in EventViewer) is re-mapped with `insert+left_control` in Karabiner Elements
- `help+left_shift` is re-mapped with `insert+left_shift`

**Comment by ycraaron** [comment]
Just tried using insert and it works.
