### ISSUE TITLE
Fn key not functional in Filco Majestouch 2 when connected via Bluetooth

### ISSUE THREAD

**Issue by Kovensky** [tekezo/Karabiner-Elements#590]
It does appear to work when connected via USB, but this keyboard otherwise majorly misbehaves when connected via USB on a Mac so I am stuck having to use it via Bluetooth :cry:

After starting Karabiner-Elements, the "Function Keys" remapping does appear to work when "Use all F1, F2, etc. keys as standard function keys" is disabled. However, holding the Fn key and pressing a key (say, F1) produces no event at all in Karabiner-EventViewer.

Changing the option to enabled lets F1, F2 be used as standard function keys, but holding Fn+F1 still  produces no event.

This only seems to happen with F1, F2, F3, F5, F6, F7, F8 and F12, which have native Fn behaviors (volume up, volume down, mute, previous, pause, stop, next, sleep, respectively). F4 and Fn+F4 always produce the F4 event, for example, and not launchpad with Fn+F4 as configured in Function Keys.

**Comment by SerhiyMakarenko** [comment]
I can confirm that behavior for Filco Majestouch 2 connected to the Mac via Bluetooth. I faced of with same issue.

**Comment by MysteryAngle** [comment]
same question.

**Comment by carlsmith** [comment]
On the USB-only version of the Filco Majestouch MINILA, the Function key doesn't work as a regular Mac Fn key. It just changes the layer in hardware, so holding it and hitting F1 will emit the same code as F1 on a regular keyboard. The MINILA does not emit any codes when you just press the Function key on its own. 

Can you please confirm that the Function key emits its own code on the full-size Majestouch when it's the only key pressed?

**Comment by carlsmith** [comment]
Just out of interest, do you have an ANSI, ISO or JIS Majestouch, and what doesn't work when it's connected over USB? I'm trying to learn as much as possible about popular mechanical keyboards on Mac.

**Comment by seagle0128** [comment]
Same issue with my Macbook Pro 2015 and Filco 104 red.
fn key doesn't work well, no matter whether I check "Use F1, F2, etc. keys as standard function keys" or not.

@carlsmith I am using ANSI Majestouch over Bluetooth. Same issue with USB, I suppose. After starting Karabiner-Elements and press fn key, no output in Karabiner Event viewer.

**Comment by Kovensky** [comment]
I am using a JIS Majestouch 2 Convertible.

When connected via USB, it behaves as if there is a ridiculous amount of packet loss. Pressing keys is extremely unreliable, and pressing is detected maybe 50% of the time; it also often doesn't detect that keys have been _released_ and ends up spamming repeats.

<kbd>F1</kbd> emits its own code when it's the only key pressed, but no code when the <kbd>Fn</kbd> key is held with it. When it emits a code, it lists `Fn` as its flag in EventViewer. If I disable "Use F1, F2, etc. keys as standard function keys" in the mac settings, it shows up as `display_brightness_decrement` instead (as it is overridden by karabiner, which would end up rather inconvenient as the "multimedia" keys in the majestouch are in a different order than in the built-in mac keyboard).

**Comment by JohnReddyZhang** [comment]
I just got a Majestouch Convertible and trying out Karabiner Elements, it has the same issue as described. `F1`, `F2`, `F3`, `F5`, `F6`, `F7`, and `F8` and `F12` has manufacture built-in functions: volume up, down, mute, rewind, start/pause, stop (which Karabiner EventViewer cannot recognize), forward, sleep (cannot recognize), thus messing up with settings.

When using function setup like below (with `Use F1, F2, etc...` checked, 
<img width="1003" alt="2019-02-16 22 16 26" src="https://user-images.githubusercontent.com/15935574/52908292-83110980-3238-11e9-98ad-a17af0c77681.png"> pressing `Fn + F*` emits those volume up, down, etc events excepts the two that cannot be recognized, and pressing only function keys emits normal `F*` keys.

When unchecked, pressing only function keys emits those keys set. But pressing `Fn + F*` cannot emit `F*`. Instead emits manufacturer set keys on keys described above, and the remapped keys on other keys, I cannot get `F*` keys to work!

**Comment by ssh352** [comment]
same issue on Realforce R2 keyboard

**Comment by uchuugaka** [comment]
This is sadly a common issue with hard FN keys I have directly observed on the following keyboards:

- Filco Camouflage-R
- Filco Majestouch Convertible 2
- Filco Minila
- Archiss Maestro 2F/2S
- Archiss ProgresTouch Retro
- E-Yoosoo (all boards)
- 

…and I am _**sure**_ _**many**_ others.

Basically, any boards that use the FN key for layers not controlled by the OS, will often exhibit this horrible problem, because they do not send a scan code for the FN key at all when the FN key alone is pressed. They only send the code for a specific key when FN and some key on the board are pressed together. 
This means they should be more honest and advertise it as a different key than FN because it is not a true FN key at all.

If you are capable with hardware, and willing to void the warranty (let's face it, the manufacturers aren't going to give you much support for keyboards) you can either hack it yourself, by bridging it in some cases or use a shim (micro controller replacement). http://1upkeyboards.com/ sells some of these shims. 

If more keyboard manufacturers would open up their firmware, users would have more choice to purchase devices with good hardware.

**Comment by ssh352** [comment]
> 

realforce r2 PFU
