### ISSUE TITLE
Does not wake up from sleep mode.

### ISSUE THREAD

**Issue by a-triant** [tekezo/Karabiner-Elements#64]
With 0.90.34 version running computer cannot wake up by pressing any button of the keyboard, i can wake it up only with a mouse, normally it should wake u with keyboard too.

**Comment by aleksandrs-ledovskis** [comment]
Try pressing `Power` button for 1-2 seconds. At least it works for me this way

**Comment by chankonabe** [comment]
I have this issue too for "Display Sleep".

**Comment by mengxuanxiangu** [comment]
I have the same issue too

**Comment by tekezo** [comment]
Thank you for feedback!

I confirmed this issue.
I'll fixed this issue.
Please use mouse click to wake until this issue has been fixed.

**Comment by modkaffes** [comment]
From what I've noticed, the mac doesn't *not* wake up when pressing the keyboard. The backlight just doesn't fire up. If you write your password and press enter, it unlocks.

Also I've noticed that the backlight opens when you press either the power button or the launchpad button (F4).

**Comment by mafredri** [comment]
I believe my macbook is no longer going to sleep, I'm unsure if it's because of Karabiner-Essentials or not but I believe it might relate to this issue.

I believe this is slightly more nuanced than the keyboard not waking the mac up. The keyboard does not activate the mac, but since the mac is not in sleep (I suspect) all keyboard input is forwarded. That means that you can start typing your password at any time (even after supposed sleep) and it will not have missed a single key (previously one key would wake the mac up and not produce any input). Using an external mouse activates the screen(s) though and you can see that you've typed your password / logged in.

Karabiner seems to have this effect on both external and the internal keyboard on my macbook.

**Comment by modkaffes** [comment]
Hm, @mafredri, useful insight. I hadn't noticed if my mac had actually gone to sleep or not, because I'm turning off the display on demand by a hot corner. Most probably mine didn't ever go to sleep either.

**Comment by runar** [comment]
I’m also having this issue with the keyboard not waking up my Mac, and like @mafredri I can type my password, then press the touchpad or mouse, and my Mac will be unlocked.

Is there any way to check if my Mac is actually sleeping? My console is full of messages similar to this, which makes it look like it does in fact go to sleep:

```
default	14:19:00.835781 +0200	identityservicesd	System going to slee
```

**Comment by wwwjfy** [comment]
I think this is fixed in the latest (0.90.47), please check.

**Comment by a-triant** [comment]
Yes now it works, thanks!

**Comment by a-triant** [comment]
Yes now it works, thanks!
