### ISSUE TITLE
Caps lock getting activated all the time.

### ISSUE THREAD

**Issue by aristidesfl** [tekezo/Karabiner-Elements#666]
The CapsLock light keeps turning on and off all the time, even when trackpad is clicked. Password inputs also signal the caps lock to be on momentarily.

KE 0.90.91
Sierra 10.12.3

<img width="780" alt="screen shot 2017-03-16 at 01 22 19" src="https://cloud.githubusercontent.com/assets/208149/23976290/0778304e-09e7-11e7-833c-3b96bda345bb.png">

<img width="912" alt="screen shot 2017-03-16 at 01 22 43" src="https://cloud.githubusercontent.com/assets/208149/23976304/1a090b5c-09e7-11e7-9c82-39e261a79641.png">

**Comment by carlsmith** [comment]
I have a similar issue, but it only happens when Caps Lock is on. The indicator LED (on each keyboard) often goes out for a moment when I click stuff with a mouse or trackpad. It seems to happen whenever the click focuses or defocuses a text field. When focussing a text field, the LED goes out for about 200 milliseconds, and when defocussing a field, it's about 600 milliseconds. It seems to be exactly the same each time, like a timer is being set.
