### ISSUE TITLE
Karabiner-Elements blocking certain inputs in Rocksmith

### ISSUE THREAD

**Issue by lszinv** [tekezo/Karabiner-Elements#673]
This seems to be the only application that I run into this with. So basically, the game Rocksmith 2014 seems to have issues with taking keyboard inputs when karabiner-elements is on. I can do most keyboard inputs, but they have an in-game search field that ignores all my keyboard inputs when I try to type into it.

Before, I used to be able to just quit KE before I launched the game. But that no longer seems to work, and I basically have to remove the application from being launched on boot first. 

I reazlize that the an input field within a game isn't really directly something you that would be of concern, but now that I can't just simply quit the app to have it work is kind of troublesome.

**Comment by ura14h** [comment]
I face same issue too.

Rocksmith 2014 Guitarcade does not recognize keyboard inputs when Karabiner-Elements is running only.

**Comment by Adirael** [comment]
Same here.

In older versions quitting Karabiner-Elements would be a temporary fix, but right now that is not enough, since the karabiner_grabber is respawned by launchctl. 

Stopping the daemon and quitting Karabiner-Elements is working at the moment. Don't forget to load the daemon again once you're done so Karabiner works again!

`sudo launchctl unload /Library/LaunchDaemons/org.pqrs.karabiner.karabiner_grabber.plist`
