### ISSUE TITLE
Key codes not showing up in EventViewer

### ISSUE THREAD

**Issue by anandman** [tekezo/Karabiner-Elements#731]
I have a Microsoft Universal Foldable Keyboard which is technically incompatible with macOS but has Windows and iOS modes (along with Android). Depending on the mode, all the keys do something when paired with the corresponding OS, but when paired with macOS, I can't get EventViewer to display keyboard events for some keys. Examples in iOS mode: Esc, Search, Home, Lock. Examples in Windows mode: Fn, Search, Lock. I'm assuming since they keyboard does stuff correctly when paired with the correct OS, it is sending key codes but macOS is dropping them somewhere.

My main goal is to remap the Ctrl, Home, Alt/Option, and Fn/Cmd keys so that they work like the built in laptop keys (Fn, Ctrl, Option, Cmd). To do that, I need these missing events.

![d74545d5-6249-46bc-b6a3-ac81aa7fdc1d](https://cloud.githubusercontent.com/assets/18639357/25764899/e8cfb6dc-319e-11e7-8dd3-fd02cfaa13de.jpg)

**Comment by LunchtimeLegend** [comment]
i'm in a similiar situation. i have a microsoft comfort keyboard which contains several additional keys, such as play/pause, vol+, vol-, stop, mute, home, zoom+, zoom-, etc.  
these used to work prior to sierra using the old microsoft drivers and some trickery - but since updating to sierra, i've been looking for an alternative way of mapping the keys.

in keyviewer, these simply don't show up at all. 

how can i catch those missing events?

thanks,

---
craig

**Comment by ksmoker** [comment]
I have a similar question. In my case, I have an OMotion keyboard with an iOS "Home" key in place of the Esc key. Was hoping I could remap this key back to a standard escape, but it does not show up at all in the keyviewer.
