### ISSUE TITLE
Karabiner for NUMLOCK fix

### ISSUE THREAD

**Issue by raj-blippar** [tekezo/Karabiner-Elements#773]
Hi, I have been using the following in the Karabiner private.xml in El Capitan for my QuickFire TK Keyboard.
````
<?xml version="1.0"?>
<root>
    <devicevendordef>
        <vendorname>CM_Storm</vendorname>
        <vendorid>0x2516</vendorid>
    </devicevendordef>
    
    <deviceproductdef>
        <productname>QuickFire_TK</productname>
        <productid>0x0011</productid>
    </deviceproductdef>
    <item>
        <name>Quickfire TK</name>
        <identifier>private.quickfiretk</identifier>
        <device_only>DeviceVendor::CM_Storm, DeviceProduct::QuickFire_TK</device_only>
        <autogen>
            __KeyToKey__ KeyCode::KEYPAD_CLEAR, KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK
        </autogen>
    </item>
</root>
````

How do I get the same working in Karabiner-Elements in Sierra? Can't I?

**Comment by carrigmore** [comment]
Hi @raj-blippar , I have the exact same keyboard and same issue as yours. I have created https://github.com/tekezo/Karabiner-Elements/issues/719. I don't think you can get the same working in Karabiner-Elements for now. Without this feature the numberpad of compact keyboard like TK-Storm or TK Stealth or other similar brands/models won't function correctly.  I hope @tekezo will have a chance to take care of this. He is quite busy now. We need to be patient. 

I brought a new Mac mini which shipped with 10.12 OX. Because OS 10.12 cannot use the Karabiner, I have to downgrade it to 10.10. 

Thanks.

**Comment by appbead** [comment]
Any progress?

**Comment by appbead** [comment]
Can any one give me some hints or documents about the structure of Karabiner-Elements, so that I can work on to add/fix such feature?

**Comment by ssh352** [comment]
I have a realforce 87u and want to use the embedded numpad via the NumLock key.
