### ISSUE TITLE
Adjust Natural Scroll Direction for External Mouse Only

### ISSUE THREAD

**Issue by nfarrar** [tekezo/Karabiner-Elements#793]
This is circumstantially related to #792

In OSX, under System Preferences -> Trackpad you have an option to enable or disable the "Scroll direction: Natural" setting. When using the trackpad, I like this to be enabled, however when using an external mouse, I like this disabled. OSX does not provide the capability to do set this for specific devices, so I manually switch this depending on how/where I'm using my MacBook.

Does Karabiner have the capability to detect whether the trackpad or external mouse is currently being used and adjust accordingly?

**Comment by pickx** [comment]
This used to be a feature in Karabiner but is not yet implemented in Karabiner-Elements.

For now, if you're also using BetterTouchTool, the dev has recently implemented this feature (under Advanced Settings -> Mouse -> General), or you can use [https://pilotmoon.com/scrollreverser/](Scroll Reverser).

**Comment by idbrii** [comment]
See also #302.

**Comment by RiZKiT** [comment]
A perfect OS wide solution was discussed in 2015 https://discussions.apple.com/thread/6931667, to bad it's abondoned.

**Comment by danteissaias** [comment]
+1

**Comment by EasyDanger** [comment]
Karabiner was suggested to me for this very feature. Presumably, Karabiner isn't compatible with Catilina? That's disappointing, since this was the primary reason I was seeking out the software

**Comment by ajgriffy** [comment]
@EasyDanger I downloaded BetterTouchTool and got it to work! I had also just downloaded Karabiner for this purpose and was disappointed. The app is compatible with Catalina but it does not have this feature in that version. Scroll Reverser is incompatible with Catalina as shown on their site:
https://pilotmoon.com/scrollreverser/

As mentioned above, in BetterTouchTool, the dev has recently implemented this feature (under Advanced Settings -> Normal Mouse -> General). In your normal System Settings for Trackpad, keep it checked as "Natural", then check this reversal box in BTT and you should be good to go. I'm using a Bluetooth non-Apple mouse, hence Normal Mouse, otherwise I think there's an Apple Mouse setting.

FYI, Karabiner Elements (KEY) wasn't a total disappointment for me. It gave me the option of mapping my unused caps lock key to my more frequently used control or option keys, so that was nice. It has some other nifty features if you're unsatisfied with the existing configurable options.

**Comment by EasyDanger** [comment]
I'm sure I'll find other uses for Karabiner. The button layout on my external keyboard is literally unusable in its default state, so I've already found some success by remapping several keys. 

I found out the hard way that ScrollReverser isn't compatible with Catalina. Reading is fundamental. >.>

**Comment by cakey** [comment]
> FYI, Karabiner Elements (KEY) wasn't a total disappointment for me. It gave me the option of mapping my unused caps lock key to my more frequently used control or option keys, so that was nice. It has some other nifty features if you're unsatisfied with the existing configurable options.

For those coming from google, you can already do this natively with settings->keyboard->modifier keys

**Comment by jensbodal** [comment]
> I'm sure I'll find other uses for Karabiner. The button layout on my external keyboard is literally unusable in its default state, so I've already found some success by remapping several keys.
> 
> I found out the hard way that ScrollReverser isn't compatible with Catalina. Reading is fundamental. >.>

I'm currently using scroll reverser on Catalina, the dev does say it's inconsistent but you need to manually add an additional permission

> For Scroll Reverser to work you will need to have it enabled in both the Accessibility and Input Monitoring lists under System preferences → Security & Privacy → Privacy

I might need to checkout BetterTouchTool.

One semi-related thing, I keep seeing karabiner settings for remapping home/end keys to `command+right` and `command+left`.  I found better results with remapping them to `control+a` and `control+e` respectively. The shift modifications I've left using command+arrow functionality.

**Comment by space-chicken** [comment]
Mos is compatible with Big Sur. It also has a smooth scrolling option that makes the scroll more or less how it's like on Windows.
[https://github.com/Caldis/Mos](url)

**Comment by jonahclarsen** [comment]
I would really love this feature too. These other solutions don't work as I want it reversed only when Cmd is held down, which those apps don't offer.

**Comment by davidleejy** [comment]
Karabiner-Elements is now able to change the mouse scroll wheel direction independently of the trackpad's scroll direction:

Karabiner-Element settings > Devices > find the mouse device you want to affect > Enable "Modify events" > Enable "Flip mouse vertical wheel".

I checked that this works in Karabiner-Elements version 14.13.0.

Additionally, for users with multiple mice, I believe Karabiner now also lets users independently modify each mice's settings, including scroll wheel direction – so that mouse A can have "natural scroll" while mouse B has "inverted scroll".
