### ISSUE TITLE
Installing Karabiner Elements Disables Command-Tab and Copy-Paste

### ISSUE THREAD

**Issue by ceridwen** [tekezo/Karabiner-Elements#823]
I installed Karabiner Elements 0.91.6 through Homebrew to see if I could turn the menu key on my external Microsoft keyboard into something functional for Emacs.  When I did that, though, I noticed that Command-Tab and pasting with keyboard shortcuts didn't work.  I suspect the alt-to-command mapping is globally disabled, but I didn't verify all the possible shortcuts.

* Microsoft Natural Ergonomic Keyboard, recognized as "Natural Ergonomic Keyboard 4000".
* Mac OS X 10.12.5 on a Macbook Pro.

**Comment by doitlikepruett** [comment]
I have the same issue and the same keyboard. Did you find a solution?

**Comment by ceridwen** [comment]
Sadly, no, I haven't.  I've tried a couple of times, the problem's still there last I checked, and I haven't been able to work around it.

**Comment by ceridwen** [comment]
Last I checked, this problem still exists, unfortunately.

**Comment by gibfahn** [comment]
@ceridwen so did you have <kbd>Command</kbd> and <kbd>Option</kbd> defined in `System Preferences -> Keyboard -> Modifier Keys`?

If so Karabiner disables those mappings, as it can't work with them (it's in "Limitations" in [the docs](https://pqrs.org/osx/karabiner/document.html)). You can get exactly the same result though by just doing the same mappings in karabiner elements, e.g.

![image](https://user-images.githubusercontent.com/15943089/39958711-9e85dbb2-55fe-11e8-898e-f4de4ea92dc8.png)

**Comment by soberman** [comment]
I have the very same issue and suggestion above doesn't work. Furthermore, when I try to copy/paste keyboard types special characters instead. And this is for every key combination.

**Comment by gibfahn** [comment]
@soberman does <kbd>Cmd</kbd>-<kbd>c</kbd> print ç and <kbd>Cmd</kbd>-<kbd>v</kbd> print √? If so that means your <kbd>Cmd</kbd> key is actually an <kbd>Option</kbd> key.

You can check by running Karabiner-Eventviewer and seeing which keypresses are registered for each key (`left_gui` is <kbd>Cmd</kbd> and `left_alt` is <kbd>Option</kbd>):

![image](https://user-images.githubusercontent.com/15943089/41497255-97c36a7c-7149-11e8-95c8-888f1d96356c.png)

If doing the modifications I suggested in https://github.com/tekezo/Karabiner-Elements/issues/823#issuecomment-388561395 doesn't work, can you post a screenshot matching the one in that comment?

**Comment by jenlampton** [comment]
This issue is still valid. I just updated from a previous version, and copy/paste broke immediately. Is there no attempt to retain previous settings between versions? 

Here's a screenshot of the interface shown in #823 (I tried to copy/paste the link, but I can't becasue copy/paste is broken. *sad trombone*)

<img width="986" alt="Screen Shot 2020-09-18 at 8 40 39 AM" src="https://user-images.githubusercontent.com/397895/93617457-d99d7700-f98a-11ea-8c7f-b36703a8dd53.png">

**Comment by bronkristian-beep** [comment]
<img width="997" height="571" alt="Image" src="https://github.com/user-attachments/assets/a9ebe8c5-e7ed-42b8-9816-f1a0775195af" />

August 2025 FIX
I have a fix and it's quite simple.
1) Open Karabiner Elements
2) In Simple Modifications select "fn" in the first box (or "left_control" for PC keyboards)
3) Select "left_command" for the second box

DONE!

You will see "left_control" in my first box because I'm using a PC keyboard with my Mac Mini M4
Hope this helps!
