### ISSUE TITLE
mouse support

### ISSUE THREAD

**Issue by sbarex** [tekezo/Karabiner-Elements#83]
Any chance to support also mouse actions?
I need to change fn+left click to middle click
thanks

**Comment by FlorinMotoc** [comment]
+1 for this. Mouse support would be great :)

**Comment by Modi34** [comment]
hope there will be ability to modify scroll wheel

I used modification keys + mouse wheel for different tasks like tab switching etc

**Comment by AJLivine** [comment]
I noticed pointing_button has been added to types and there's a pointing_button_manager. I don't know how to translate the code into what you need to put in karabiner.json, but it looks like if you can build from source (I haven't been able to due to code-signing errors) and figure out what to put in karibiner.json you might be able to get mouse support right now.

If anyone can figure it out, please report! :)

**Comment by Windedhiker** [comment]
Thank you so much for your help with this project. I am newly disabled as I was rear ended and without this code, I would not be able to use my Logitech Wave keyboard. I went from only being able to use a keyboard for 15-20 minutes per day to hours.

I have a Logitech Trackman Marble and since installing Karabiner - Elements, I noticed my middle click mouse button does not work. I tried setting a custom config in system preferences but I did not work. 

Thanks!

**Comment by incandescentman** [comment]
This should work:

                        {
                            "from": {
                                "key_code": "keypad_2"
                            },
                            "to": {
                                "pointing_button": "button1"
                            }
