### ISSUE TITLE
External keyboard command/option swap

### ISSUE THREAD

**Issue by NekR** [tekezo/Karabiner-Elements#830]
When I just open Karabiner-Elements without any configuration it swaps command-left/option-left key on my external (Windows) keyboard.

I'm not sure what's wrong actually, maybe old options of Karabiner persist somehow because by default I have Keyboards Alt as Command and Windows key as Option. That's what I configured in Karabiner back on El Capitan.

**Comment by h-nn-ng** [comment]
![bildschirmfoto 2017-07-14 um 08 35 38](https://user-images.githubusercontent.com/13087104/28201029-72b896aa-686f-11e7-9741-1ff2c7614a3a.png)
--> https://github.com/tekezo/Karabiner-Elements

**Comment by starsy** [comment]
@NekR https://github.com/starsy/Karabiner-Elements allows you configure mappings for different devices within a single profile, so you can swap your cmd/option keys on external keyboards only, while keeps internal keyboard's layout not changed.

**Comment by armen52** [comment]
So far I have only been able to figure out how to exclude the laptop's built-in keyboard entirely from  having any customization applied to it by Karabiner-Elements.

@starsy is it possible to apply _some_ key customizations to the laptop keyboard, and apply others to an external keyboard, all under the same profile? If so, I have not been able to figure it out. Could you explain how to do so?

**Comment by starsy** [comment]
@armen52 original KBE doesn't provide this functionality, I have made some enhancements on the original one to support it. Please try this fork: https://github.com/starsy/Karabiner-Elements screenshot on configurations should be self-explanatory, but please let me know if any questions.

**Comment by armen52** [comment]
@starsy thanks, I missed the fact that you were referring to a forked version. I will give your version a try as, in my eyes, this is pretty important functionality for an app like KBE to have. 

Have you sent a PR for incorporating this functionality into the original KBE repo, or has the maintainer there disclosed any plans to incorporate this feature into KBE? I am concerned about using a fork over the long run.

**Comment by starsy** [comment]
@armen52 totally agree this is an important feature. yes, i have sent the PR a while ago, however @tekezo is not giving opinions on that, to accept or reject, that's why i had to maintain the fork and keeps following the changes. @tekezo is neither showing that he will add this feature into the main repo or not.

**Comment by armen52** [comment]
@starsy For some reason, after restarting my system, your forked version seems to prevent all keyboard input from both the internal and external keyboard. I had to start up in safe mode to be able to use my computer and uninstall it. I could not even log in.

The first time it happened I installed your version right after uninstalling the tekezo version, but I had not restarted after the uninstall. I assumed it was because of some crossover between versions. I removed all versions, restarted, then installed your fork again. It seemed to work fine for a few days, but after another system restart, I had the same issue (no keyboard input whatsoever).

Have you run into this issue? Do you know the fix or workaround?

**Comment by starsy** [comment]
@armen52 which release are you using? there do exist such issue in the earlier versions which inherited from original version. i would recommend using https://github.com/starsy/Karabiner-Elements/releases/tag/v0.91.4 , I have been using it on my 2016 RMBP, Sierra 10.12.6 for a month without any issues. the latest version (v0.91.10) once has the stuck key issue when awaking from sleep, waiting for original to be stabilized.

**Comment by starsy** [comment]
@armen52 as a workaround, just to start Karabiner app and manually quite Karabiner from the simple_modification tab, the keyboard would restore responding.

**Comment by wincent** [comment]
See: https://github.com/tekezo/Karabiner-Elements/commit/fd90e595e1d8c1cf972e6694b85be294b773954c

**Comment by armen52** [comment]
@starsy I installed your fork using Karabiner-Elements-0.91.1-starsy.dmg.

If I understand the commit @wincent just linked to correctly, it looks like this change (or this functionality) will make it into an official release soon. I guess I will just wait for that. Thanks.

**Comment by wincent** [comment]
@armen52: `device_if`/`device_unless` is already in a release. Works with `complex_modifications`, and based on comment from @tekezo in another issue, I believe it will be made to work in some way for `simple_modifications` too.
