### ISSUE TITLE
Feature Request: Ability to set mods per keyboard

### ISSUE THREAD

**Issue by jeffhatz** [tekezo/Karabiner-Elements#904]
I have a MacBook with a regular Apple keyboard that only has one or two customizations (like flipping Caps and Esc). When I'm at my desk, I have a Windows Das Keyboard that needs a lot of hacks to make it work properly.

Currently, every time I switch to/from my desk, I have to change profiles. I don't need separate profiles, I just need modifications to be specific to certain keyboards. I would like to see a feature where I could target customizations to certain keyboards. So it doesn't matter what keyboard I'm using, Karabiner will be smart enough to know what applies where.

**Comment by starsy** [comment]
@jeffhatz use this fork before @tekezo implement it in the main repo: https://github.com/starsy/Karabiner-Elements

**Comment by wincent** [comment]
v0.91.12 already supports this, at least for `complex_modifications` (and you can always express a `simple_modification` in terms of a complex one). See [the changelog](https://github.com/tekezo/Karabiner-Elements/blob/master/NEWS.md).

There is more work ongoing on the master branch to bring this to the other parts of the config outside of `complex_modifications`.

This issue is one of several dupes for this feature, BTW. Search for "device" and you will find several (such as #550, #547, #792 etc).

**Comment by jeffhatz** [comment]
v0.91.12 fixes this perfectly!! Thanks!
