### ISSUE TITLE
Karabiner Elements vs. the Play Button (F8)

### ISSUE THREAD

**Issue by RobertoMinelli** [tekezo/Karabiner-Elements#923]
Hi guys, 

First of all I'd like to thank you for your work!

I would like to use `Karabiner-Elements` to fix an issue of Mac OS that I really hate. Long story short, I want the three keys `Play (F8)`, `Preview (F7)`, and `Next (F9)` to work **only** in `Spotify`, no matter the frontmost app.

I decomposed my problem in these four steps:

1. Stop launching `iTunes` automatically when pressing the `Play Button (F8)` while in the `Finder` (or also in other apps);

2. Disable `Play (F8)`, `Preview (F7)`, and `Next (F9)` keys in `iTunes`; 

3. Disable the `Play Button (F8)` in `Apple Keynote` (by default it will start the presentation);

4. _Forward_ the `Play Button (F8)` from `Apple Keynote`—or other apps—to `Spotify`.

I managed to solve points 2. and 3. by adding two `complex modifications` in `karabiner.json` to replace the respective key with  `vk_none `. It follows a sample condition:

```json
{
    "conditions": [
        {
            "bundle_identifiers": [
                "^com\\.apple\\.iTunes$"
            ],
            "type": "frontmost_application_if"
        }
    ],
    "from": {
        "key_code": "f8",
        "modifiers": {
            "optional": [
                "any"
            ]
        }
    },
    "to": [
        {
            "key_code": "vk_none"
        }
    ],
    "type": "basic"
}
```

However, I would be super happy if you could kindly help me in points 1 and 4.

Thank you **very much** in advance for your help, and please keep up the good work!

Roberto

P.s. I attach my config file [karabiner.json](https://github.com/tekezo/Karabiner-Elements/files/1230482/karabiner.json.txt) for further reference.

**Comment by RobertoMinelli** [comment]
Anyone? This is really crucial to me :(

**Comment by kamykaze** [comment]
@RobertoMinelli I'm a big Karabiner-Elements supporter, but I'm afraid KE doesn't currently support sending keys to a specific app (anyone feel free to correct me if I'm wrong).

Until KE adds that capability, may I suggest you look into [BetterTouchTool](https://www.boastr.net/) ? It can capture gestures (including keyboard keys) and send to a specific app. The downside is that it does not intercept keyboard key presses like KE does, so if you pressed play, it would still trigger iTunes.

Proposed workaround:

1. in KE: Remap F7, F8, F9 to three obscure key combinations (eg: Ctrl+Alt+Shift+F7, etc.) so that pressing those keys will no longer do anything in iTunes, Keynote, etc.
2. in BTT: Remap the obscure keys Ctrl+Alt+Shift+F7 to Prev, Play, Next using 'Send shortcut to App' action

Note: media keys may not be usable by BTT. If that's the case, use alternative shortcuts (like Cmd+Left Arrow for Prev) instead

**Comment by RobertoMinelli** [comment]
Thank you very much for your answer @kamykaze. I'll look into what you suggested! I believe that sending keys to apps would be a nice feature to add to KE :) The iTunes Play Button problem is pretty annoying for many Mac OS users.

**Comment by RobertoMinelli** [comment]
Another question: Is there a way to tell KE to disable a key, i.e., mapping it to `vk_none` for all apps except one?

**Comment by kamykaze** [comment]
you can try making two rules...one to map a key to itself (for a specific app), and a generic one to map it to vk_none

**Comment by RobertoMinelli** [comment]
@kamykaze, is there a way to _prioritize_ rules? If I create a general rule and remap `f8` to `vk_none` other specific rules have no effect :(

**Comment by BillTribble** [comment]
Sorry to resurrect this thread - did you ever get this fixed Roberto? 

I just tried installing your code above, but sadly it won't work on my 2016 MBP with touchstrip ... :/  If anyone can provide a pointer on how to access the touchstrip media keys I'd be much obliged.

Many thanks!

**Comment by lachieh** [comment]
I've had a crack at this to fix @RobertoMinelli's number 1.

Basically, hold `f8` to launch spotify, then on keyup, press the play/pause key. This means you can still accidentally open itunes if you don't hold `f8` down, but if you're unsure, holding it will open Spotify, or bring it to the front if it is open.

```json
{
    "description": "Open Spotify on hold of f8",
    "manipulators": [
        {
            "from": {
                "key_code": "f8",
                "modifiers": {
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "vk_none"
                }
            ],
            "to_after_key_up": [
                {
                    "key_code": "play_or_pause"
                }
            ],
            "to_if_held_down": [
                {
                    "shell_command": "open '/Applications/Spotify.app'",
                    "repeat": false
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by lachieh** [comment]
@RobertoMinelli, to answer your question on priorities, yes, you can do this using conditions. Karabiner-Elements will match the first manipulator. If you have multiples on the same 'from' key code, only the first will trigger.

I tried looking into this (i.e. setting a variable on first press and opening spotify, then pressing `play_or_pause` if the variable is set) but the problem is that if spotify closes, there's no way of changing that variable back to prevent iTunes from ever opening.

**Comment by ralphcallaway** [comment]
kind of got this working, albeit highly convoluted way. general idea
- disable default media key behavior by unloading rdc.app
- add shell scripts with apple script for playpause, next track, prev track
- add a karabiner rule to wire f7/f8/f9 to those scripts

**Comment by ralphcallaway** [comment]
@lachieh thinking about your approach you could switch the shell command to use apple script to tell spotify to playpause / prev / next when the keys are held down

**Comment by joostk90** [comment]
I've tried an approach similar to @ralphcallaway last year. However, it never worked as I tried acting upon <kbd>play_or_pause</kbd> instead of <kbd>F8</kbd>, then I found this thread. 

The following works without auxiliary scripts:

```js
{
    "description": "Toggle Spotify play/pause",
    "manipulators": [
        {
            "from": {
                "key_code": "f8"
            },
            "to": [
                {
                    "shell_command": "osascript -e 'tell application \"Spotify\" to playpause'"
                }
            ],
            "type": "basic"
        }
    ]
}
```

AppleScript `tell application "Spotify"` will also start Spotify if it was not running. I did not include remapping <kbd>F7</kbd> nor <kbd>F9</kbd> as I think one would only use those keys when media - chiefly via Spotify - is already playing, in which case iTunes will be left alone. And that also removed the requirement to unload `com.apple.rcd` as suggested in https://github.com/ralphcallaway/Mac-Spotify-Play-Pause-Lock.

**Comment by Haderach999** [comment]
I know this is a pretty stale thread, and I know this doesn't use Karabiner Elements at all, but it effectively accomplishes the end goal of stopping Itunes (Music) from running, and replacing it with Spotify. 

Just install "noTunes" at the link below:
https://github.com/tombonez/noTunes/blob/master/README.md

Then, run the following command in Terminal, to replace Itunes Music with "Spotify", when the "Play/Pause" media button is pressed (F8):
defaults write digital.twisted.noTunes replacement /Applications/Spotify.app

Once Spotify's opened, music has to be manually started by clicking Play, but then the media button will work correctly from that point onward.
