### ISSUE TITLE
Where to find karabiner.json?

### ISSUE THREAD

**Issue by impala75** [tekezo/Karabiner-Elements#950]
Hello,

Please, I'd like to customize Karabiner Elements (by adding a rule changing fn+letter to left_command+letter), but I cannot find the karabiner.json file. The given information is that it is here: ~/.config/karabiner/karabiner.json
You will probably laugh, but first I looked for it in the Finder, for quite a while. Then I thought it was likely a command and remembered there was a Terminal. So I have just entered it in there but it does not work.

Could somebody please explain me how to open karabiner.json? I am a novice on OS X (and more generally with commands).

**Comment by thomasjachmann** [comment]
It's a file, not a command, but you won't find it in the Finder, since Finder hides hidden files per default. Files with names starting with a `.` are considered hidden files in unix like systems. That's why you cannot even find the `.config` directory in Finder.

So, Terminal.app is the right choice. In there, you type: `open ~/.config`, this will open the hidden `.config` directory in a new Finder window. There you can navigate to `karabiner/karabiner.json` and open/edit that file with your favorite editor.

**Comment by impala75** [comment]
Thank you Thomas!
Yes, what I meant was that a command was needed to open this file; but I did not really know how to open that config directory.
Thanks again, I could open it, find the file and create my customization.
I will close the subject.

**Comment by XstrongMen** [comment]
Thank you too :-)
