### ISSUE TITLE
Key debounce

### ISSUE THREAD

**Issue by jcrippen** [tekezo/Karabiner-Elements#972]
The old Karabiner had an option to debounce keypresses when the keyboard was sending too many keydown or keyup events within a certain period of time. It would be nice to have that back in this new edition.

**Comment by azoff** [comment]
👍

**Comment by jrop** [comment]
Sorry to ping an old issue, but I would still find this appealing.

**Comment by pinei** [comment]
Try debounce-mac
https://github.com/toothbrush/debounce-mac/

Solved my problem with mechanical keyboard "chatter"

**Comment by dvdplm** [comment]
I would love for this to be re-opened and implemented in Karabiner, still very much a problem still. Thanks! :)

**Comment by deadalnix** [comment]
Well, add. me to the list of people sad to not have this feature anymore.

Note that you can. emulate. some debounce using `to_if_held_down_threshold_milliseconds` but this doesn't work well because it adds a delay before the key. press, with is very unfortunate.

One would want the first event to register, and subsequent events to be swallow if they fit the debounce criteria.
