### ISSUE TITLE
Mouse Key

### ISSUE THREAD

**Issue by threescales** [tekezo/Karabiner-Elements#981]
I have already can't do without it.
If it's not possible with Karabiner-Elements yet, do you know any alternatives to achieve the above?

![image](https://user-images.githubusercontent.com/15061441/30357853-89a0040a-9873-11e7-967a-e2734fb41765.png)

**Comment by wviana** [comment]
I'm getting the same problem. I would like to use the mouse from the keyboard. I've tried from v1 and v4 mouse keys. Have no Idea how to make it work. Any tips?

**Comment by tekezo** [comment]
Mouse keys are available since the latest beta version.
You can use them from complex_modifications.
https://pqrs.org/osx/karabiner/complex_modifications/#mouse_keys_simple

How to upgrade to the latest beta version:
![Check for beta updates](https://pqrs.org/osx/karabiner/img/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by wviana** [comment]
Oh, sure, I got it yesterday night. 
Sorry for not updating here.

Is beta really stable?

**Comment by wviana** [comment]
It may be closed
