### ISSUE TITLE
Microsoft Remote Desktop Beta

### ISSUE THREAD

**Issue by reekes** [tekezo/Karabiner-Elements#988]
Short story...
Microsoft has a much improved version of the remote desktop app, called "Microsoft Remote Desktop Beta". To use the wonderful "Swap command and control" complex modifier you have to change the "bundle_identifiers" in the .json file.

1) Import the Swap command and control for remote desktop complex modifier.

2) Duplicate the .json (in the hidden location)

3) Change all occurrences of "com\\.microsoft\\.rdc\\.mac" to "com\\.microsoft\\.rdc\\.osx\\.beta"

4) Change the description (e.g. add the word "beta") so you know it's targeting the newer version.

Long story...
I use Windows RDS from my Mac most of the day, and searched for a way to swap Cmd and Cntl keys. I *only* want to do this while in RDS. Attempts to modify the keyboard layout on Windows failed. I suspect it's because the remapping it done on Windows by intercepting USB. But (again I suspect) RDS is not sending USB keycodes. So none of the Windows tools will let me remap the Apple and Windows modifier keys when I'm using a Mac with RDS.

I think the Apple keyboard preferences used to let us modify keys for specific apps, but no longer. So it seems the *only* tool that can do the solve the problem above is Karabiner.

It took me too much time trying to find where the .json config files are located. Please make this more obvious in the documentation.

The new Microsoft Remote Desktop Beta includes the option to make the Cut, Copy, Paste options to the Cmd key (instead of the Windows key). I'd call that less than ideal. I keep ending up typing the Apple Cmd key by itself, which in RDS is the Windows key. That being up the start menu, argh! I often need to use the Select All command, which in RDS is Windows-a (or Cntl-a on the Mac while using RDS). Cmd-a in Windows 10 brings up the "Action Center." Cmd-f brings up the Feedback option. Way too difficult and my muscle memory is causing too much grief to try and change my touch typing skills. So simply providing Cut, Copy, Paste is basically no help at all.

I need to swap all Cmd and Cntl events. Thank you for the very useful tool!!!

**Comment by cajhin** [comment]
Hi, this is a bit meta, I hope y'all don't mind...

I've been doing these things for a long time. I don't use your approach, because I try hard to NOT move keystrokes around, because that breaks muscle memory.
Let's say I want to hit ctrl-c to stop a script. Then I hit ctrl-c. You on the other hand must first consider if your script is local or remote, and hit cmd-c or ctrl-c.

My solution is to explicitly map all important shortcuts on Windows. For your RDP session that would be:
cmd-c to ctrl-c
cmd-a to ctrl-a 
...and so on, for every global shortcut I use. 
Now cmd-c ALWAYS copies, and ctrl-t does whatever the forground app defines.

This will obviously override the native Windows shortcuts. When you map "LEFT_cmd-a" to "ctrl-a", you can still press right_cmd-a to trigger "win-a" (action center).

Because [reasons] I also run AutoHotkey scripts on my Windows machines. It's a nice and powerful tool, but life is easier when you can have only one config (Karabiner in your case).

AHK scripts are quickly created and look like this:
LeftWin & c :: Send ^c 
<#d::Run "cmd.exe"    ;short syntax for: leftWin+D opens dos box

**Comment by reekes** [comment]
cajhin, I'm not a Windows person. I'm a software engineer and have been on the Mac and Linux all my life. Windows is new, and I'm only using it for software development on Server 2016. And only with RDP from my Mac. The problem for me and my muscle memory is Mac and Windows basically swap the Cmd and Cntl keys. I'm on a Mac, using Windows (via Desktop Remote). My muscle memory is for all commands (e.g. copy, paste, undo, select all) use the Apple Command modifier key closest to the space bar (but that is the Cntl key on Windows). That's how the Mac works (and how I've been doing it since 1984).

To type the Windows "command" it's the Apple Cntl key, which is the furthest key from the space bar. I'm not just fighting my muscle memory, it's also an awkward key combination to type. I'm switching back and forth, quickly, on my Mac from a Mac application to a Windows application. Swapping the Cntl and Cmd key *only* while I'm in the Windows application solves the problem. It's a simple fix with Karabiner. It's just one change.

Here's what I need. I want the Windows key to be mapped to the Apple Command key, in all cases. I also want the Apple Cntl key to always been the Windows Cntl key. I don't know how to do this with AHK.

I tried AHK and couldn't make it work. It would swap the two keys, but then failed in my PowerShell and PowerShell ISE. After some searching, I found the problem is because my PowerShell is running as admin. I found out I have to run the AHK script as admin to make it work in my PowerShell and PS ISE.

But even that didn't work. Pressing the Apple Command key alone normally triggers the Windows key, which brings up the Start menu. After running my AHK script, pressing either of the two keys alone worked as I expected. Pressing the Cntl key on my Mac keyboard acts like the Windows key and brings up the start menu. So far so good.

But typing Cmd-A doesn't select all. Instead, it ends up typing the "a" into PowerShell ISE. Same problem with Cmd-Z, which should undo but types the "z". So I don't understand how to use AHK to map the two modifier keys. The entire AHK script I tried is:

LCtrl::LWin
LWin::LCtrl


Q: How would I use AHK to swap the Windows and Cntl key, and function properly as modifier keys? This is for Windows 10, and to work in all applications even if they're run as admin.

**Comment by cajhin** [comment]
I think you've messed up something with the ctrl key.
I just tried it out: no Karabiner on the Mac, remote desktop into a Win10 box, replaced the AHK script with your two lines.

Result: it works. The CMD and STRG keys are switched (both stand-alone and as modifiers for other keys).
Cmd+a selects all in powershell. Ctrl+D shows the Windows desktop.

I never had issues with AHK and admin. I'm local admin on all Win boxes, but I start AHK normally (without admin credentials). The only place where it doesn't work, by design, is the Windows security panels (modal dialog over blurry desktop "do you want to allow this application to steal all your moneys bla?").

You say that Ctrl is the leftmost key? On a Mac, that should be 'Fn', no??
When I press Fn+A in PowerShell, I get an 'a'... I think your modifier keys are already switched somehow. 
(BTW, I intentionally switch Ctrl and Fn because Apple made the wrong choice there, IMO. Ctrl belongs into the corner...)

**Comment by reekes** [comment]
Without Karabiner running, my two line AHK script fails.

LCtrl::LWin
LWin::LCtrl

Within PS ISE on my Mac via Remote Desktop, if I type...

Cmd key alone I get nothing (instead of the usual Windows key which brings up the startup menu)
Cntl key alone I get the Windows key press and it brings up the startup menu
Cntl-a I get the Action Centre
Cmd-a I get "a"
Cmd-a and then releasing keys and type Cmd-a again I get another "a"
Cmd-a a second time *while continuing to hold the Cmd key* I get Select All
Cmd-a and I get "a" and while continuing to hold the Cmd key I type o then I get the Open File dialog

In other words, to get Cmd to act like a modifier I first have to hold it down then type a letter. That puts types the letter (bad). But if I keep holding it down and type again, then that letter is interpreted as a modified key.

Karabiner is working better, but I find it has conflicts with SteerMouse on my Mac. It's also worrisome that Karabiner is always running, intercepting keys, when I only need this effect while in Windows Remote Desktop.


BTW - On my Mac keyboard, the left most key on the bottom row is Control. Then Option, and then next to the space bar it's Command. It's been this way on all my keyboards since I can remember. I always use the Apple desktop keyboard with numeric keypad. That one is a close match to an industry standard keyboard. They're laid out [like this](https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english?fnode=6a2c390ff944c1bdee90f081599ce4d8f2ecf25c016952e754f57112110b45c628d556255aaebd86dc2f2a85b264c35c0a52a7be4b8dbcddc7c82b5980cac3ce850a6e5b76fbae93de6b2c687901281520eb368589b95f988a686ff43a1a5728).
